In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/sample_data/KBO increased data edited.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   WAR     301 non-null    float64
 1   AB      301 non-null    int64  
 2   R       301 non-null    int64  
 3   HR      301 non-null    int64  
 4   TB      301 non-null    int64  
 5   RBI     301 non-null    int64  
 6   BB      301 non-null    int64  
 7   IB      301 non-null    int64  
 8   SF      301 non-null    int64  
 9   AVG     301 non-null    float64
 10  OBP     301 non-null    float64
 11  SLG     301 non-null    float64
 12  OPS     301 non-null    float64
 13  wRC+    301 non-null    float64
dtypes: float64(6), int64(8)
memory usage: 33.0 KB


In [4]:
df = df.astype('float32')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   WAR     301 non-null    float32
 1   AB      301 non-null    float32
 2   R       301 non-null    float32
 3   HR      301 non-null    float32
 4   TB      301 non-null    float32
 5   RBI     301 non-null    float32
 6   BB      301 non-null    float32
 7   IB      301 non-null    float32
 8   SF      301 non-null    float32
 9   AVG     301 non-null    float32
 10  OBP     301 non-null    float32
 11  SLG     301 non-null    float32
 12  OPS     301 non-null    float32
 13  wRC+    301 non-null    float32
dtypes: float32(14)
memory usage: 16.6 KB


In [6]:
df.describe()

WAR          AB           R          HR          TB         RBI  \
count  301.000000  301.000000  301.000000  301.000000  301.000000  301.000000   
mean     0.659601  166.790695   25.707642    4.777409   70.039864   24.362125   
std      1.453971  178.446564   29.534166    7.994182   85.357307   31.318661   
min     -1.350000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     -0.180000   15.000000    2.000000    0.000000    4.000000    1.000000   
50%      0.040000   84.000000   12.000000    1.000000   28.000000    8.000000   
75%      1.060000  305.000000   43.000000    7.000000  123.000000   41.000000   
max      8.320000  574.000000  143.000000   46.000000  352.000000  132.000000   

               BB          IB          SF         AVG         OBP         SLG  \
count  301.000000  301.000000  301.000000  301.000000  301.000000  301.000000   
mean    17.491693    0.498339    1.754153    0.226498    0.302169    0.328023   
std     20.571445    1.290027    2.559820    0.111155    0.123197    0.178639   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000    0.000000    0.000000    0.185000    0.261000    0.238000   
50%      8.000000    0.000000    0.000000    0.248000    0.326000    0.345000   
75%     31.000000    0.000000    3.000000    0.286000    0.367000    0.427000   
max     96.000000    9.000000   13.000000    0.667000    0.667000    1.000000   

              OPS        wRC+  
count  301.000000  301.000000  
mean     0.630193   61.901657  
std      0.284303   85.309853  
min      0.000000 -154.500000  
25%      0.522000   31.900000  
50%      0.678000   77.900002  
75%      0.791000  107.900002  
max      1.667000  380.299988

In [8]:
# train set과 test set 분리
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

In [10]:
# 예측 변수와 타깃값 분리
X = train_set.drop("WAR", axis=1).to_numpy()
y = train_set["WAR"].copy().to_numpy()
X, y

(array([[ 4.05e+02,  5.70e+01,  7.00e+00, ...,  3.65e-01,  7.16e-01,
          8.64e+01],
        [ 4.40e+01,  1.20e+01,  0.00e+00, ...,  2.50e-01,  5.33e-01,
          3.08e+01],
        [ 9.50e+01,  1.30e+01,  2.00e+00, ...,  3.89e-01,  7.09e-01,
          7.99e+01],
        ...,
        [ 3.70e+01,  3.00e+00,  0.00e+00, ...,  1.35e-01,  2.89e-01,
         -4.39e+01],
        [ 1.83e+02,  2.30e+01,  0.00e+00, ...,  2.90e-01,  5.69e-01,
          4.14e+01],
        [ 5.90e+01,  6.00e+00,  1.00e+00, ...,  2.71e-01,  5.71e-01,
          6.17e+01]], dtype=float32),
 array([ 1.01, -0.22, -0.15, -0.24, -0.07,  2.13, -0.04,  1.54, -0.19,
         3.2 , -0.19, -0.8 , -0.01,  3.98, -0.22,  0.82, -0.08,  0.1 ,
         1.53,  0.67,  4.7 ,  5.16,  0.5 ,  0.16, -0.19,  3.23, -0.07,
         3.08, -0.21, -0.08,  2.4 , -0.15,  0.16,  0.72, -0.41, -0.05,
        -0.21, -0.52,  1.59, -0.01,  0.3 , -1.35, -0.92,  1.18,  0.62,
        -0.29,  0.97, -0.03,  2.03, -0.24,  0.16, -0.05,  1.8 , -0.33,
    

In [11]:
# 스케일링
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)

In [31]:
import tensorflow as tf
W = tf.Variable(tf.random.normal([13, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [13]:
# 비용함수 정의
def loss_fn(model, features, labels):
  hypothesis = model(features)
  cost = tf.reduce_mean(tf.square(hypothesis - labels))
  return cost

In [32]:
learning_rate = 0.1

In [15]:
def predict(X):
    return tf.matmul(X, W) + b

In [33]:
epochs = 100000

for i in range(epochs):
    with tf.GradientTape() as tape:
        cost = loss_fn(predict, X_scaled, y)

    W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if (i > 10000) and (i % 1000 == 0):
        learning_rate = learning_rate * 0.8

    if i % 100 == 0:
        print(f'{i} loss: {loss_fn(predict, X_scaled, y)}')

0 loss: 10.812396049499512
100 loss: 2.2970266342163086
200 loss: 2.272791862487793
300 loss: 2.2668509483337402
400 loss: 2.264596700668335
500 loss: 2.2632832527160645
600 loss: 2.2623291015625
700 loss: 2.261579751968384
800 loss: 2.2609739303588867
900 loss: 2.260477066040039
1000 loss: 2.260066270828247
1100 loss: 2.2597239017486572
1200 loss: 2.25943660736084
1300 loss: 2.2591943740844727
1400 loss: 2.258988618850708
1500 loss: 2.2588138580322266
1600 loss: 2.2586634159088135
1700 loss: 2.2585344314575195
1800 loss: 2.258422613143921
1900 loss: 2.2583255767822266
2000 loss: 2.2582411766052246
2100 loss: 2.258167028427124
2200 loss: 2.2581021785736084
2300 loss: 2.258044958114624
2400 loss: 2.2579944133758545
2500 loss: 2.2579495906829834
2600 loss: 2.2579097747802734
2700 loss: 2.2578744888305664
2800 loss: 2.257843017578125
2900 loss: 2.257814645767212
3000 loss: 2.2577896118164062
3100 loss: 2.2577669620513916
3200 loss: 2.257746696472168
3300 loss: 2.257728338241577
3400 loss:

KeyboardInterrupt: 

In [34]:
# 예측 생성
test_X = test_set.drop("WAR", axis=1).to_numpy()
test_X_scaled = std_scaler.fit_transform(X)
test_y = test_set["WAR"].copy().to_numpy()

predictions = tf.matmul(test_X_scaled, W) + b
predictions

<tf.Tensor: shape=(240, 1), dtype=float32, numpy=
array([[0.7127763 ],
       [0.71276766],
       [0.7127156 ],
       [0.7126657 ],
       [0.71273375],
       [0.71272135],
       [0.71270895],
       [0.71275246],
       [0.7128482 ],
       [0.7126286 ],
       [0.7127473 ],
       [0.71272373],
       [0.71265423],
       [0.7127468 ],
       [0.7128943 ],
       [0.71279603],
       [0.71262634],
       [0.7127239 ],
       [0.7127436 ],
       [0.7127956 ],
       [0.71267015],
       [0.71264184],
       [0.71272165],
       [0.7127366 ],
       [0.7127342 ],
       [0.71275556],
       [0.71275747],
       [0.71277684],
       [0.71275073],
       [0.7128982 ],
       [0.7127705 ],
       [0.7126862 ],
       [0.7126968 ],
       [0.71268636],
       [0.7126709 ],
       [0.7127804 ],
       [0.71272194],
       [0.7126591 ],
       [0.7126606 ],
       [0.7126549 ],
       [0.7127342 ],
       [0.7127158 ],
       [0.7127544 ],
       [0.7127203 ],
       [0.71272254],
     

In [35]:
corr_matrix = df.corr()
corr_matrix['WAR'].sort_values(ascending=False)

WAR     1.000000
R       0.858495
TB      0.852566
RBI     0.820191
BB      0.813487
AB      0.787215
HR      0.732417
SF      0.695182
IB      0.684790
SLG     0.464298
OPS     0.452327
wRC+    0.415908
AVG     0.398693
OBP     0.370597
Name: WAR, dtype: float64

### 득점만 가지고 linear regresssion을 해보자

In [38]:
R = train_set["R"].to_numpy()
R = R.reshape(-1, 1)
y = train_set["WAR"].copy().to_numpy()
y = y.reshape(-1, 1)

In [39]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(R, y)

LinearRegression()

In [42]:
# 정확도 판단
from sklearn.metrics import root_mean_squared_error

WAR_predictions = lin_reg.predict(R)

lin_rmse = root_mean_squared_error(y, WAR_predictions)
lin_rmse

0.745343

In [44]:
R_test = test_set["R"].to_numpy()
R_test = R_test.reshape(-1, 1)
WAR_labels_test = test_set["WAR"].copy().to_numpy()
WAR_labels_test = WAR_labels_test.reshape(-1, 1)

final_predictions = lin_reg.predict(R_test)

final_rmse = root_mean_squared_error(WAR_labels_test, final_predictions)
final_rmse

0.74571544

In [45]:
# 황재균 WAR 예측
hwang = lin_reg.predict([[60]])
hwang

array([[2.16771805]])

In [46]:
# 로하스 WAR 예측
Rojas = lin_reg.predict([[108]])
Rojas

array([[4.25224864]])

In [47]:
# 김도영 WAR 예측
DO_YEONG = lin_reg.predict([[143]])
DO_YEONG

array([[5.77221887]])

### 득점, 타점만 가지고 예측해보자

In [49]:
R = train_set["R"].to_numpy()
R = R.reshape(-1, 1)

RBI = train_set["RBI"].to_numpy()
RBI = RBI.reshape(-1, 1)

R_AND_RBI = np.concatenate((R, RBI), axis=1)

y = train_set["WAR"].copy().to_numpy()
y = y.reshape(-1, 1)


In [50]:
# 훈련 시작
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(R_AND_RBI, y)

LinearRegression()

In [51]:
WAR_predictions = lin_reg.predict(R_AND_RBI)

WAR_predictions[:5]

array([[ 2.0181131 ],
       [ 0.01870415],
       [ 0.06221676],
       [-0.01871103],
       [-0.39378777]], dtype=float32)

In [52]:
y[:5]

array([[ 1.01],
       [-0.22],
       [-0.15],
       [-0.24],
       [-0.07]], dtype=float32)

In [53]:
# 정확도 판단
from sklearn.metrics import root_mean_squared_error

lin_rmse = root_mean_squared_error(y, WAR_predictions)
lin_rmse

0.73829526

In [54]:
R_test = test_set["R"].to_numpy()
R_test = R_test.reshape(-1, 1)

RBI_test = test_set["RBI"].to_numpy()
RBI_test = RBI_test.reshape(-1, 1)

R_AND_RBI_test = np.concatenate((R_test, RBI_test), axis=1)

y_test = test_set["WAR"].copy().to_numpy()
y_test = y_test.reshape(-1, 1)

final_predictions = lin_reg.predict(R_AND_RBI_test)

final_rmse = root_mean_squared_error(y_test, final_predictions)
final_rmse

0.72806805

In [56]:
# 황재균 WAR 예측
hwang = lin_reg.predict([[60, 58]])
hwang

array([[2.16518759]])

In [57]:
# 로하스 WAR 예측
Rojas = lin_reg.predict([[108, 112]])
Rojas

array([[4.30340271]])

In [58]:
# 에레디아 WAR 예측
Heredia = lin_reg.predict([[82, 118]])
Heredia

array([[3.43666202]])

In [59]:
# 강백호 WAR 예측
BaekHo = lin_reg.predict([[92, 96]])
BaekHo

array([[3.60720102]])