In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/sample_data/KBO increased data edited.csv')

In [4]:
df.sort_values(by=['AB'], ascending=False, ignore_index=True)

WAR   AB    R  HR   TB  RBI  BB  IB  SF    AVG    OBP    SLG    OPS  \
0    3.40  574   88  15  293  111  46   2  11  0.352  0.394  0.510  0.904   
1    6.50  572  108  32  325  112  88   9   4  0.329  0.421  0.568  0.989   
2    3.42  552   92  26  285   97  41   4   5  0.310  0.359  0.516  0.875   
3    2.12  550   92  26  264   96  59   4   2  0.289  0.360  0.480  0.840   
4    8.32  544  143  38  352  109  66   7   7  0.347  0.420  0.647  1.067   
..    ...  ...  ...  ..  ...  ...  ..  ..  ..    ...    ...    ...    ...   
296 -0.01    1    0   0    0    1   1   0   0  0.000  0.500  0.000  0.500   
297 -0.02    1    0   0    0    0   0   0   0  0.000  0.000  0.000  0.000   
298 -0.03    1    0   0    0    0   0   0   0  0.000  0.000  0.000  0.000   
299 -0.03    1    0   0    0    0   0   0   0  0.000  0.000  0.000  0.000   
300 -0.02    1    0   0    0    0   0   0   0  0.000  0.000  0.000  0.000   

      wRC+  
0    127.5  
1    153.3  
2    121.2  
3    112.3  
4    172.5  
..     ...  
296  130.2  
297 -127.9  
298 -151.2  
299 -127.9  
300 -130.7  

[301 rows x 14 columns]

In [6]:
df.describe()

WAR          AB           R          HR          TB         RBI  \
count  301.000000  301.000000  301.000000  301.000000  301.000000  301.000000   
mean     0.659601  166.790698   25.707641    4.777409   70.039867   24.362126   
std      1.453971  178.446517   29.534176    7.994183   85.357318   31.318659   
min     -1.350000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     -0.180000   15.000000    2.000000    0.000000    4.000000    1.000000   
50%      0.040000   84.000000   12.000000    1.000000   28.000000    8.000000   
75%      1.060000  305.000000   43.000000    7.000000  123.000000   41.000000   
max      8.320000  574.000000  143.000000   46.000000  352.000000  132.000000   

               BB          IB          SF         AVG         OBP         SLG  \
count  301.000000  301.000000  301.000000  301.000000  301.000000  301.000000   
mean    17.491694    0.498339    1.754153    0.226498    0.302169    0.328023   
std     20.571439    1.290025    2.559822    0.111155    0.123197    0.178639   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000    0.000000    0.000000    0.185000    0.261000    0.238000   
50%      8.000000    0.000000    0.000000    0.248000    0.326000    0.345000   
75%     31.000000    0.000000    3.000000    0.286000    0.367000    0.427000   
max     96.000000    9.000000   13.000000    0.667000    0.667000    1.000000   

              OPS        wRC+  
count  301.000000  301.000000  
mean     0.630193   61.901661  
std      0.284303   85.309843  
min      0.000000 -154.500000  
25%      0.522000   31.900000  
50%      0.678000   77.900000  
75%      0.791000  107.900000  
max      1.667000  380.300000

## Remove low AB

In [7]:
# 타석수 적은 선수는 제거
df.drop(df[df['AB'] < 10].index, inplace=True)

In [8]:
df.describe()

WAR          AB           R          HR          TB         RBI  \
count  245.000000  245.000000  245.000000  245.000000  245.000000  245.000000   
mean     0.819796  203.942857   31.432653    5.861224   85.795918   29.816327   
std      1.567942  178.046425   29.921081    8.498621   87.279131   32.330183   
min     -1.350000   10.000000    0.000000    0.000000    0.000000    0.000000   
25%     -0.210000   36.000000    6.000000    0.000000   11.000000    3.000000   
50%      0.150000  141.000000   21.000000    2.000000   46.000000   15.000000   
75%      1.520000  366.000000   53.000000    9.000000  148.000000   50.000000   
max      8.320000  574.000000  143.000000   46.000000  352.000000  132.000000   

               BB          IB          SF         AVG         OBP         SLG  \
count  245.000000  245.000000  245.000000  245.000000  245.000000  245.000000   
mean    21.391837    0.612245    2.155102    0.243527    0.321208    0.355310   
std     20.929466    1.405731    2.681224    0.068051    0.070349    0.123082   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      3.000000    0.000000    0.000000    0.204000    0.283000    0.282000   
50%     14.000000    0.000000    1.000000    0.256000    0.333000    0.368000   
75%     36.000000    1.000000    3.000000    0.291000    0.365000    0.429000   
max     96.000000    9.000000   13.000000    0.407000    0.471000    0.667000   

              OPS        wRC+  
count  245.000000  245.000000  
mean     0.676518   75.367755  
std      0.179126   49.525243  
min      0.000000 -132.200000  
25%      0.582000   50.300000  
50%      0.711000   84.600000  
75%      0.795000  107.900000  
max      1.080000  183.700000

In [9]:
# 타석수 적은 선수는 제거
df.drop(df[df['AB'] <= 30].index, inplace=True)

In [10]:
df.describe()

WAR          AB           R          HR          TB         RBI  \
count  191.000000  191.000000  191.000000  191.000000  191.000000  191.000000   
mean     1.083927  256.136126   39.209424    7.439791  108.481675   37.759162   
std      1.680480  168.155418   29.496799    9.015501   86.204032   32.460091   
min     -1.350000   31.000000    1.000000    0.000000    4.000000    0.000000   
25%     -0.170000  101.500000   13.000000    1.000000   34.500000   10.000000   
50%      0.510000  234.000000   33.000000    4.000000   87.000000   30.000000   
75%      1.975000  406.000000   60.000000   10.500000  182.000000   58.500000   
max      8.320000  574.000000  143.000000   46.000000  352.000000  132.000000   

              BB          IB          SF         AVG         OBP         SLG  \
count  191.00000  191.000000  191.000000  191.000000  191.000000  191.000000   
mean    26.86911    0.780105    2.722513    0.257393    0.332539    0.378440   
std     20.60630    1.550491    2.779903    0.053694    0.053478    0.104888   
min      1.00000    0.000000    0.000000    0.088000    0.154000    0.125000   
25%      9.50000    0.000000    0.000000    0.231500    0.301000    0.307000   
50%     21.00000    0.000000    2.000000    0.264000    0.339000    0.383000   
75%     44.50000    1.000000    4.000000    0.294000    0.369000    0.448000   
max     96.00000    9.000000   13.000000    0.360000    0.447000    0.660000   

              OPS        wRC+  
count  191.000000  191.000000  
mean     0.710979   84.202618  
std      0.146777   39.769539  
min      0.289000  -43.900000  
25%      0.609500   61.200000  
50%      0.732000   91.500000  
75%      0.805500  108.950000  
max      1.080000  183.700000

In [11]:
df.to_csv('/content/sample_data/KBO increased data_over 30 AB.csv')

## NonLinear SVM & Hyperparameter RandomSearch

In [12]:
# train set과 test set 분리
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

In [13]:
# train set과 dev set 분리
train_set, dev_set = train_test_split(train_set, test_size=0.33, random_state=42)

In [14]:
R = train_set["R"].to_numpy()
R = R.reshape(-1, 1)

RBI = train_set["RBI"].to_numpy()
RBI = RBI.reshape(-1, 1)

R_AND_RBI = np.concatenate((R, RBI), axis=1)

y = train_set["WAR"].copy().to_numpy()
y = y.reshape(-1, 1)

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint


full_pipeline = Pipeline([
    ("StandardScaler", StandardScaler()),
    ("SVR", SVR(kernel='poly')),
    ])

param_distribs = {'SVR__degree': randint(low=2, high=10),
                  'SVR__C': np.random.uniform(0.01, 0.1, size=10),
                  'SVR__epsilon': np.random.uniform(0.01, 0.1, size=10),
                  }

rnd_search = RandomizedSearchCV(full_pipeline, param_distributions=param_distribs, n_iter=10, cv=3,
                                 scoring='neg_mean_squared_error', random_state=42)

rnd_search.fit(R_AND_RBI, y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('SVR', SVR(kernel='poly'))]),
                   param_distributions={'SVR__C': array([0.05555434, 0.03695992, 0.03098859, 0.08620909, 0.02971599,
       0.04676148, 0.04152076, 0.02803852, 0.0843611 , 0.04728989]),
                                        'SVR__degree': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x79aa942cccd0>,
                                        'SVR__epsilon': array([0.07865483, 0.05072013, 0.03115128, 0.07212688, 0.05577655,
       0.06195866, 0.09587485, 0.09620705, 0.08352026, 0.03042373])},
                   random_state=42, scoring='neg_mean_squared_error')

In [24]:
rnd_search.best_params_

{'SVR__C': 0.02971599228445214,
 'SVR__degree': 3,
 'SVR__epsilon': 0.09620704577097068}

In [25]:
final_model = rnd_search.best_estimator_

In [26]:
R_test = test_set["R"].to_numpy()
R_test = R_test.reshape(-1, 1)

RBI_test = test_set["RBI"].to_numpy()
RBI_test = RBI_test.reshape(-1, 1)

R_AND_RBI_test = np.concatenate((R_test, RBI_test), axis=1)

In [27]:
from sklearn.metrics import root_mean_squared_error

y_test = test_set["WAR"].copy().to_numpy()
y_test = y_test.reshape(-1, 1)

final_prediction = final_model.predict(R_AND_RBI_test)
final_rmse = root_mean_squared_error(y_test, final_prediction)
final_rmse

0.8339853983757514

In [28]:
# 황재균 WAR(-0.30) 예측
hwang = final_model.predict([[60, 58]])
hwang

array([0.95610002])

In [29]:
# 로하스 WAR(6.50) 예측
Rojas = final_model.predict([[108, 112]])
Rojas

array([6.44644064])

In [30]:
# 김도영 WAR(8.32) 예측
DO_YEONG = final_model.predict([[143, 109]])
DO_YEONG

array([11.78747725])

In [31]:
# 최정 WAR(4.55) 예측
Choi_Jung = final_model.predict([[93, 107]])
Choi_Jung

array([4.32051161])

In [32]:
# 강백호 WAR(2.12) 예측
BaekHo = final_model.predict([[92, 96]])
BaekHo

array([3.37499654])

In [33]:
# 모델 저장
import joblib
joblib.dump(final_model, "rnd_hyperparameter_svm_poly_reg_with_R_and_RBI_model.pkl")

['rnd_hyperparameter_svm_poly_reg_with_R_and_RBI_model.pkl']