In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/KBO_24_STAT_edited.csv')

In [4]:
df.head()

WAR  oWAR   PA   AB    R  HR   TB  RBI  BB  HP  ...  GDP  SH  SF    AVG  \
0  8.32  8.51  625  544  143  38  352  109  66   7  ...   10   1   7  0.347   
1  6.50  6.34  670  572  108  32  325  112  88   6  ...   10   0   4  0.329   
2  6.13  5.83  602  527   88  19  273  104  64   3  ...    5   0   8  0.340   
3  5.69  5.61  568  493   92  33  309  115  55  12  ...    6   2   6  0.343   
4  5.16  4.47  567  509   90  11  233   75  47   4  ...    6   0   7  0.326   

     OBP    SLG    OPS  R/ePA   wRC+       SSR  
0  0.420  0.647  1.067  0.232  172.5  0.909091  
1  0.421  0.568  0.989  0.211  153.3  0.666667  
2  0.409  0.518  0.927  0.191  148.9  1.000000  
3  0.417  0.627  1.044  0.228  162.3  0.764706  
4  0.383  0.458  0.841  0.160  124.1  0.833333  

[5 rows x 22 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   WAR     50 non-null     float64
 1   oWAR    50 non-null     float64
 2   PA      50 non-null     int64  
 3   AB      50 non-null     int64  
 4   R       50 non-null     int64  
 5   HR      50 non-null     int64  
 6   TB      50 non-null     int64  
 7   RBI     50 non-null     int64  
 8   BB      50 non-null     int64  
 9   HP      50 non-null     int64  
 10  IB      50 non-null     int64  
 11  SO      50 non-null     int64  
 12  GDP     50 non-null     int64  
 13  SH      50 non-null     int64  
 14  SF      50 non-null     int64  
 15  AVG     50 non-null     float64
 16  OBP     50 non-null     float64
 17  SLG     50 non-null     float64
 18  OPS     50 non-null     float64
 19  R/ePA   50 non-null     float64
 20  wRC+    50 non-null     float64
 21  SSR     50 non-null     float64
dtypes: f

In [7]:
df.describe()

WAR       oWAR          PA          AB           R         HR  \
count  50.000000  50.000000   50.000000   50.000000   50.000000  50.000000   
mean    3.255000   3.173200  546.540000  477.400000   78.280000  17.280000   
std     1.513566   1.432089   54.833034   52.222835   17.536015  10.362885   
min     1.010000   1.280000  452.000000  385.000000   48.000000   0.000000   
25%     2.170000   2.180000  498.000000  431.000000   65.250000   9.000000   
50%     3.110000   2.985000  551.000000  481.500000   78.000000  15.500000   
75%     3.980000   3.880000  592.500000  520.500000   89.750000  23.500000   
max     8.320000   8.510000  670.000000  574.000000  143.000000  46.000000   

              TB         RBI         BB         HP  ...        GDP         SH  \
count   50.00000   50.000000  50.000000  50.000000  ...  50.000000  50.000000   
mean   223.88000   79.700000  53.440000   7.560000  ...   8.980000   2.460000   
std     49.31268   23.275852  13.825679   5.345836  ...   3.656082   3.459444   
min    138.00000   36.000000  28.000000   0.000000  ...   2.000000   0.000000   
25%    190.25000   61.000000  46.250000   3.250000  ...   6.000000   0.000000   
50%    205.50000   78.000000  51.500000   7.000000  ...   8.500000   1.000000   
75%    257.25000   96.750000  62.500000  10.000000  ...  11.000000   3.000000   
max    352.00000  132.000000  96.000000  25.000000  ...  17.000000  15.000000   

              SF        AVG        OBP        SLG        OPS      R/ePA  \
count  50.000000  50.000000  50.000000  50.000000  50.000000  50.000000   
mean    5.660000   0.296980   0.373100   0.466100   0.839200   0.159240   
std     2.832825   0.028125   0.027695   0.070571   0.082552   0.027033   
min     0.000000   0.246000   0.316000   0.357000   0.695000   0.112000   
25%     4.000000   0.275000   0.356250   0.418000   0.789500   0.143250   
50%     5.500000   0.295500   0.370000   0.459500   0.828000   0.156500   
75%     7.000000   0.313500   0.384000   0.498250   0.873500   0.172750   
max    13.000000   0.360000   0.447000   0.647000   1.067000   0.232000   

             wRC+        SSR  
count   50.000000  50.000000  
mean   118.358000   0.724108  
std     19.877452   0.210866  
min     86.100000   0.000000  
25%    104.550000   0.587500  
50%    113.600000   0.750000  
75%    129.675000   0.851190  
max    172.500000   1.000000  

[8 rows x 22 columns]

In [8]:
corr_matrix = df.corr()
corr_matrix['WAR'].sort_values(ascending=False)

WAR      1.000000
oWAR     0.962085
wRC+     0.794448
R/ePA    0.767448
OPS      0.720858
OBP      0.650701
R        0.634545
AVG      0.631346
TB       0.610284
SLG      0.587879
IB       0.495281
RBI      0.448901
PA       0.443548
HR       0.382364
BB       0.370283
AB       0.357869
SF       0.314309
SSR      0.176194
HP       0.025475
GDP      0.012521
SO      -0.006329
SH      -0.145127
Name: WAR, dtype: float64

In [9]:
df.drop(['oWAR'], axis=1, inplace=True)

In [10]:
df.head()

WAR   PA   AB    R  HR   TB  RBI  BB  HP  IB  ...  GDP  SH  SF    AVG  \
0  8.32  625  544  143  38  352  109  66   7   7  ...   10   1   7  0.347   
1  6.50  670  572  108  32  325  112  88   6   9  ...   10   0   4  0.329   
2  6.13  602  527   88  19  273  104  64   3   2  ...    5   0   8  0.340   
3  5.69  568  493   92  33  309  115  55  12   4  ...    6   2   6  0.343   
4  5.16  567  509   90  11  233   75  47   4   2  ...    6   0   7  0.326   

     OBP    SLG    OPS  R/ePA   wRC+       SSR  
0  0.420  0.647  1.067  0.232  172.5  0.909091  
1  0.421  0.568  0.989  0.211  153.3  0.666667  
2  0.409  0.518  0.927  0.191  148.9  1.000000  
3  0.417  0.627  1.044  0.228  162.3  0.764706  
4  0.383  0.458  0.841  0.160  124.1  0.833333  

[5 rows x 21 columns]

In [11]:
df.drop(['R/ePA'], axis=1, inplace=True)

In [12]:
df.head()

WAR   PA   AB    R  HR   TB  RBI  BB  HP  IB   SO  GDP  SH  SF    AVG  \
0  8.32  625  544  143  38  352  109  66   7   7  110   10   1   7  0.347   
1  6.50  670  572  108  32  325  112  88   6   9  115   10   0   4  0.329   
2  6.13  602  527   88  19  273  104  64   3   2   82    5   0   8  0.340   
3  5.69  568  493   92  33  309  115  55  12   4   73    6   2   6  0.343   
4  5.16  567  509   90  11  233   75  47   4   2   62    6   0   7  0.326   

     OBP    SLG    OPS   wRC+       SSR  
0  0.420  0.647  1.067  172.5  0.909091  
1  0.421  0.568  0.989  153.3  0.666667  
2  0.409  0.518  0.927  148.9  1.000000  
3  0.417  0.627  1.044  162.3  0.764706  
4  0.383  0.458  0.841  124.1  0.833333

In [13]:
corr_matrix = df.corr()
corr_matrix['WAR'].sort_values(ascending=False)

WAR     1.000000
wRC+    0.794448
OPS     0.720858
OBP     0.650701
R       0.634545
AVG     0.631346
TB      0.610284
SLG     0.587879
IB      0.495281
RBI     0.448901
PA      0.443548
HR      0.382364
BB      0.370283
AB      0.357869
SF      0.314309
SSR     0.176194
HP      0.025475
GDP     0.012521
SO     -0.006329
SH     -0.145127
Name: WAR, dtype: float64

In [14]:
df.drop(['SSR'], axis=1, inplace=True)
df.drop(['HP'], axis=1, inplace=True)
df.drop(['GDP'], axis=1, inplace=True)
df.drop(['SO'], axis=1, inplace=True)
df.drop(['SH'], axis=1, inplace=True)

In [15]:
df.head()

WAR   PA   AB    R  HR   TB  RBI  BB  IB  SF    AVG    OBP    SLG    OPS  \
0  8.32  625  544  143  38  352  109  66   7   7  0.347  0.420  0.647  1.067   
1  6.50  670  572  108  32  325  112  88   9   4  0.329  0.421  0.568  0.989   
2  6.13  602  527   88  19  273  104  64   2   8  0.340  0.409  0.518  0.927   
3  5.69  568  493   92  33  309  115  55   4   6  0.343  0.417  0.627  1.044   
4  5.16  567  509   90  11  233   75  47   2   7  0.326  0.383  0.458  0.841   

    wRC+  
0  172.5  
1  153.3  
2  148.9  
3  162.3  
4  124.1

In [17]:
# train set과 test set 분리
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)
train_set.to_csv("KB0_24_train.csv", index = False)
test_set.to_csv("KB0_24_test.csv", index = False)

In [18]:
# 예측 변수와 타깃값 분리
WAR = train_set.drop("WAR", axis=1)
WAR_labels = train_set["WAR"].copy()

In [24]:
# StansdardScaler 사용하여 스케일링
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
WAR_scaled = std_scaler.fit_transform(WAR)

In [26]:
WAR_scaled

array([[-0.17103098, -0.41175173,  1.2689409 , -1.51053849, -1.00179021,
        -1.91256608,  0.38793123, -0.18470625, -1.76270436,  0.71663524,
         1.06679164, -1.20308248, -0.61407688, -0.297519  ],
       [ 0.41120213,  0.68756159,  0.61117456, -0.67280484,  0.22003144,
        -0.20374415, -0.56810782, -0.18470625,  0.52404724,  1.05993356,
         0.31876244, -0.12231643,  0.01204072,  0.26147838],
       [ 0.88426654,  1.15869587,  0.22747753,  1.73567941,  0.77917016,
         1.19836615, -0.42102489, -0.61930918, -1.00045382, -1.68645299,
        -1.95932648,  0.31583197, -0.43346603, -0.69960483],
       [ 0.10189079, -0.11729281,  0.77561614,  2.04982953,  1.15192931,
         1.19836615,  0.0202239 , -0.61930918,  0.52404724, -0.14161056,
         0.35276377,  1.86395631,  1.6616198 ,  1.33043827],
       [ 0.42939692,  0.37347207,  0.72080228,  1.6309627 ,  1.7939034 ,
         1.54889372,  0.0202239 ,  0.68449962,  0.14292197,  1.6435407 ,
         1.47480756,  2.34

In [27]:
# 파이프라인 생성
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('std_scaler', StandardScaler())
])

In [28]:
# 훈련 시작
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(WAR_scaled, WAR_labels)

LinearRegression()

In [29]:
WAR_predictions = lin_reg.predict(WAR_scaled)
WAR_predictions[:5]

array([3.83767384, 4.15414175, 2.45022837, 4.35493385, 5.53573279])

In [30]:
WAR_labels.iloc[:5].values

array([3.98, 5.16, 2.17, 4.55, 5.69])

In [32]:
# 정확도 판단
from sklearn.metrics import root_mean_squared_error

lin_rmse = root_mean_squared_error(WAR_labels, WAR_predictions)
lin_rmse

0.6609483095332048

In [33]:
# 결정트리로 훈련해보자.
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor()
tree_reg.fit(WAR_scaled, WAR_labels)

DecisionTreeRegressor()

In [34]:
WAR_predictions = tree_reg.predict(WAR_scaled)
tree_rmse = root_mean_squared_error(WAR_labels, WAR_predictions)
tree_rmse

0.0

In [35]:
# 오차가 없다고? 교차 검증으로 평가하기
from sklearn.model_selection import cross_val_score

scores = - cross_val_score(tree_reg, WAR_scaled, WAR_labels,
                         scoring="neg_mean_squared_error", cv=10)

In [36]:
pd.Series(scores).describe()

count    10.000000
mean      1.614280
std       0.604300
min       0.564550
25%       1.417063
50%       1.617100
75%       2.000081
max       2.544850
dtype: float64

In [37]:
# 랜덤 포레스트 사용하기
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(random_state=42)
forest_reg.fit(WAR_scaled, WAR_labels)

RandomForestRegressor(random_state=42)

In [38]:
forest_rmses = - cross_val_score(forest_reg, WAR_scaled, WAR_labels,
                         scoring="neg_root_mean_squared_error", cv=10)

In [39]:
pd.Series(forest_rmses).describe()

count    10.000000
mean      0.963394
std       0.280573
min       0.578030
25%       0.728723
50%       0.944000
75%       1.195112
max       1.400853
dtype: float64

In [40]:
# 특성의 중요도 추출
final_model = forest_reg
feature_importances = final_model.feature_importances_
feature_importances.round(2)

array([0.02, 0.02, 0.04, 0.01, 0.03, 0.01, 0.06, 0.03, 0.02, 0.44, 0.05,
       0.01, 0.04, 0.21])

In [41]:
sorted(zip(feature_importances, WAR.columns), reverse=True)

[(0.4423305487001947, 'AVG'),
 (0.2132380013822713, 'wRC+'),
 (0.056578678361214, 'BB'),
 (0.04594095496032503, 'OBP'),
 (0.04241141786626468, 'OPS'),
 (0.03689289855321092, 'R'),
 (0.03274076058402529, 'IB'),
 (0.02992346656588503, 'TB'),
 (0.024441980435829326, 'SF'),
 (0.02175855074144089, 'PA'),
 (0.019570606135443983, 'AB'),
 (0.012216776485405513, 'HR'),
 (0.011166212297772725, 'SLG'),
 (0.010789146930716545, 'RBI')]

In [42]:
# test set으로 평가하기
WAR_test = test_set.drop("WAR", axis=1)
WAR_labels_test = test_set["WAR"].copy()

WAR_test_scaled = std_scaler.transform(WAR_test)

final_predictions = final_model.predict(WAR_test_scaled)

final_rmse = root_mean_squared_error(WAR_labels_test, final_predictions)
final_rmse

0.9787226568338961

In [43]:
from scipy import stats
confidence = 0.95
squared_errors = (final_predictions - WAR_labels_test) ** 2
np.sqrt(stats.t.interval(confidence, len(squared_errors) - 1,
                         loc=squared_errors.mean(),
                         scale=stats.sem(squared_errors)))

array([0.45039475, 1.30879358])

In [44]:
# 모델 저장
import joblib
joblib.dump(final_model, "KB0_24_WAR_prediction_model.pkl")

['KB0_24_WAR_prediction_model.pkl']

In [66]:
import joblib

model = joblib.load("KB0_24_WAR_prediction_model.pkl")

new_data = WAR
predictions = model.predict(new_data)
print(predictions)

[4.6299 4.6255 4.6462 4.6462 4.5992 4.5891 4.5193 4.6462 4.6462 4.5098
 4.5992 4.6124 4.6462 4.524  4.6124 4.6061 4.6124 4.6462 4.6674 4.6124
 4.5098 4.6124 4.6674 4.5891 4.6462 4.6356 4.5596 4.6462 4.6674 4.5191
 4.6488 4.6124 4.6124 4.4641 4.6488 4.5891 4.6674 4.6462 4.4979 4.6124]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(
