In [1]:
%pip install "scikit-learn<1.6"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 75.1 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.0
    Uninstalling scikit-learn-1.6.0:
      Successfully uninstalled scikit-learn-1.6.0


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/content/sample_data/final_df.csv', index_col=0)

In [4]:
# Split train and test
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

# split features and labels
X_train = train_set.drop("WAR", axis=1).to_numpy()
y_train = train_set["WAR"].copy().to_numpy()
X_test = test_set.drop("WAR", axis=1).to_numpy()
y_test = test_set["WAR"].copy().to_numpy()

## NonLinear SVM

In [5]:
from sklearn.metrics import mean_squared_error, make_scorer
scorer = make_scorer(mean_squared_error, greater_is_better=False, squared=False)

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RandomizedSearchCV


svm_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ("SVR", SVR(kernel='poly')),
    ])

param_distribs = {'SVR__degree': np.arange(2, 11),
                  'SVR__C': np.linspace(0.01, 0.1, 10),
                  'SVR__epsilon': np.linspace(0.01, 0.1, 10),
                  }

svm_search = RandomizedSearchCV(
    svm_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


svm_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('SVR', SVR(kernel='poly'))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'SVR__C': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ]),
                                        'SVR__degree': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
                                        'SVR__epsilon': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [7]:
pd.set_option('display.max_colwidth', 10)
svm_search.cv_results_ = pd.DataFrame(svm_search.cv_results_)
svm_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
5    0.004388       0.000122      0.003783         0.001658        
1    0.003949       0.000129      0.003037         0.000122        
2    0.004494       0.000273      0.003140         0.000150        
13   0.004277       0.000188      0.003314         0.000484        
4    0.004615       0.000131      0.003313         0.001086        
7    0.006098       0.003272      0.003008         0.001538        
6    0.006071       0.001475      0.003228         0.000994        
15   0.005101       0.000466      0.004559         0.001989        
3    0.007535       0.003247      0.002952         0.000276        
10   0.004858       0.000664      0.004083         0.001540        
8    0.010739       0.008290      0.002903         0.000492        
0    0.005916       0.000433      0.003486         0.000478        
19   0.003480       0.000475      0.001918         0.000164        
16   0.008722       0.004649      0.002643         0.000074        
17   0.006293       0.001363      0.002806         0.000661        
9    0.004907       0.000678      0.002897         0.000707        
18   0.005207       0.000271      0.002216         0.000045        
11   0.010527       0.005481      0.003350         0.000362        
14   0.005148       0.000166      0.002446         0.000497        
12   0.007155       0.001700      0.003581         0.001490        

    param_SVR__epsilon  param_SVR__degree  param_SVR__C     params  \
5        0.02                   3               0.09     {'SVR_...   
1        0.08                   3               0.10     {'SVR_...   
2        0.02                   7               0.03     {'SVR_...   
13       0.01                   5               0.02     {'SVR_...   
4        0.10                   5               0.01     {'SVR_...   
7        0.01                   4               0.02     {'SVR_...   
6        0.10                   4               0.04     {'SVR_...   
15       0.01                   7               0.07     {'SVR_...   
3        0.09                   6               0.07     {'SVR_...   
10       0.10                   6               0.02     {'SVR_...   
8        0.03                   9               0.01     {'SVR_...   
0        0.01                   9               0.01     {'SVR_...   
19       0.08                   8               0.01     {'SVR_...   
16       0.09                   9               0.02     {'SVR_...   
17       0.03                   8               0.05     {'SVR_...   
9        0.07                  10               0.01     {'SVR_...   
18       0.08                  10               0.05     {'SVR_...   
11       0.04                  10               0.06     {'SVR_...   
14       0.02                  10               0.08     {'SVR_...   
12       0.02                  10               0.09     {'SVR_...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
5   -0.428794          -0.945117          -0.431153          -0.601688         
1   -0.423333          -0.972412          -0.435273          -0.610339         
2   -0.561934          -0.922750          -0.564344          -0.683009         
13  -0.674866          -0.991156          -0.511874          -0.725965         
4   -0.699401          -0.998753          -0.553005          -0.750387         
7   -0.664008          -1.161217          -0.619326          -0.814850         
6   -0.710128          -1.143201          -0.597442          -0.816924         
15  -0.685391          -1.236361          -0.621390          -0.847714         
3   -0.993322          -1.167435          -0.544574          -0.901777         
10  -1.031885          -1.190145          -0.615375          -0.945802         
8   -0.676587          -1.728804          -0.589223          -0.998205         
0   -0.670744          -1.762937          -0.587345          -1.007009         
19  -0.776528          -1.990828          -0.577650          -1.

In [8]:
svm_search.best_params_

{'SVR__epsilon': 0.020000000000000004,
 'SVR__degree': 3,
 'SVR__C': 0.09000000000000001}

In [9]:
best_svm_model = svm_search.best_estimator_

In [29]:
from sklearn.metrics import root_mean_squared_error
y_pred = best_svm_model.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.9467002429355457

In [34]:
y_pred = best_svm_model.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

1.272263222208523

In [120]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([400, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_svm_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([-1.351])

In [26]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = best_svm_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([43.89935254])

In [35]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_svm_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([-1.35099968])

In [40]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = best_svm_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([-1.35007202])

In [42]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = best_svm_model.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([-1.35083971])

## RandomForest

In [43]:
from sklearn.ensemble import RandomForestRegressor

randomforest_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('RandomForest', RandomForestRegressor(random_state=42)),
    ])

param_distribs = {
    'RandomForest__n_estimators': np.arange(10, 100),
    'RandomForest__max_depth': np.arange(4, 20),
}

randomforest_search = RandomizedSearchCV(
    randomforest_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


randomforest_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('RandomForest',
                                              RandomForestRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'RandomForest__max_depth': array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                                        'RandomForest__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [44]:
pd.set_option('display.max_colwidth', 10)
randomforest_search.cv_results_ = pd.DataFrame(randomforest_search.cv_results_)
randomforest_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
4    0.298675       0.014299      0.012521         0.001922        
18   0.129584       0.003888      0.006328         0.000870        
19   0.232224       0.042163      0.008822         0.002055        
10   0.181103       0.014827      0.007869         0.000392        
0    0.245509       0.011721      0.009580         0.000326        
16   0.229358       0.019674      0.012096         0.002226        
1    0.221163       0.012331      0.008880         0.001045        
17   0.142549       0.006923      0.008752         0.002120        
6    0.150190       0.005443      0.007621         0.000684        
13   0.158918       0.010389      0.011852         0.004371        
14   0.161668       0.000860      0.007653         0.001155        
12   0.175600       0.003760      0.008241         0.001382        
7    0.255606       0.007552      0.010027         0.000479        
5    0.211044       0.002888      0.011057         0.003359        
9    0.210812       0.008094      0.008781         0.000164        
15   0.169167       0.008205      0.007702         0.000905        
3    0.201375       0.006816      0.009377         0.000536        
11   0.093163       0.002945      0.006319         0.001076        
8    0.114614       0.000860      0.006286         0.000170        
2    0.059934       0.004931      0.004291         0.000258        

    param_RandomForest__n_estimators  param_RandomForest__max_depth  \
4          98                                10                       
18         46                                 7                       
19         90                                 7                       
10         59                                10                       
0          88                                 5                       
16         75                                11                       
1          75                                10                       
17         46                                12                       
6          50                                19                       
13         50                                14                       
14         61                                 5                       
12         63                                17                       
7          82                                19                       
5          74                                14                       
9          74                                 6                       
15         55                                18                       
3          75                                 4                       
11         35                                 5                       
8          39                                17                       
2          18                                10                       

       params  split0_test_score  split1_test_score  split2_test_score  \
4   {'Rand...  -0.332380          -0.975023          -0.324877           
18  {'Rand...  -0.342522          -0.973113          -0.321453           
19  {'Rand...  -0.341801          -0.975083          -0.320208           
10  {'Rand...  -0.346665          -0.968846          -0.328572           
0   {'Rand...  -0.350472          -0.977318          -0.319047           
16  {'Rand...  -0.353364          -0.971708          -0.323491           
1   {'Rand...  -0.352378          -0.972026          -0.324870           
17  {'Rand...  -0.346568          -0.972346          -0.331846           
6   {'Rand...  -0.349959          -0.971165          -0.330124           
13  {'Rand...  -0.350254          -0.971165          -0.330124           
14  {'Rand...  -0.359835          -0.970947          -0.321452           
12  {'Rand...  -0.357130          -0.968627          -0.326899           
7   {'Rand...  -0.357268          -0.972441          -0.324054           
5   {'Rand...  -0.356443          -0.971630    

In [45]:
randomforest_search.best_params_

{'RandomForest__n_estimators': 98, 'RandomForest__max_depth': 10}

In [46]:
best_randomforest_model = randomforest_search.best_estimator_

In [50]:
y_pred = best_randomforest_model.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.2767681295483611

In [51]:
y_pred = best_randomforest_model.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.8474352439713385

In [52]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([524, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_randomforest_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([5.79739126])

In [53]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = best_randomforest_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([4.63072955])

In [54]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_randomforest_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.27237073])

In [55]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = best_randomforest_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.68867808])

In [56]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = best_randomforest_model.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.43677977])

## Adaboost

In [57]:
from sklearn.ensemble import AdaBoostRegressor

adaboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('Adaboost', AdaBoostRegressor(random_state=42)),
    ])

param_distribs = {
    'Adaboost__n_estimators': np.arange(10, 100),
    'Adaboost__learning_rate': np.linspace(1e-4, 1e-2),
}

adaboost_search = RandomizedSearchCV(
    adaboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


adaboost_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('Adaboost',
                                              AdaBoostRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'Adaboost__learning_rate': array([0.0001    , 0.00030204, 0.00050408, 0.00070612, 0.00090816,
       0.0011102 , 0.00131224, 0.00151429, 0.00171633, 0.00191837,
       0.00212041, 0.00232245, 0.00252449, 0....
                                        'Adaboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [58]:
pd.set_option('display.max_colwidth', 10)
adaboost_search.cv_results_ = pd.DataFrame(adaboost_search.cv_results_)
adaboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
8    0.155173       0.006252      0.014542         0.001078        
14   0.190723       0.007560      0.024538         0.007988        
0    0.186695       0.011956      0.016818         0.000491        
1    0.286986       0.027970      0.029196         0.008252        
15   0.231923       0.006806      0.020600         0.000922        
5    0.101480       0.000563      0.011029         0.000329        
10   0.169510       0.003311      0.016732         0.000639        
2    0.126491       0.004574      0.013979         0.002012        
4    0.087012       0.011209      0.011484         0.001920        
17   0.114537       0.013903      0.009719         0.000235        
3    0.089191       0.003760      0.010588         0.002950        
19   0.129126       0.026742      0.010683         0.002792        
11   0.178250       0.005831      0.018094         0.001696        
9    0.240789       0.002268      0.019522         0.000464        
7    0.144579       0.003048      0.013819         0.000860        
16   0.103901       0.000881      0.011792         0.002482        
6    0.106494       0.019712      0.009893         0.000345        
18   0.036228       0.001983      0.005469         0.000220        
13   0.092177       0.015684      0.008555         0.000980        
12   0.041187       0.001768      0.007517         0.000765        

    param_Adaboost__n_estimators  param_Adaboost__learning_rate     params  \
8          50                      0.000302                      {'Adab...   
14         65                      0.007576                      {'Adab...   
0          60                      0.001918                      {'Adab...   
1          92                      0.008384                      {'Adab...   
15         77                      0.009192                      {'Adab...   
5          34                      0.007778                      {'Adab...   
10         59                      0.001716                      {'Adab...   
2          42                      0.006969                      {'Adab...   
4          26                      0.010000                      {'Adab...   
17         34                      0.001110                      {'Adab...   
3          26                      0.001110                      {'Adab...   
19         48                      0.005757                      {'Adab...   
11         61                      0.005353                      {'Adab...   
9          75                      0.003737                      {'Adab...   
7          49                      0.006565                      {'Adab...   
16         34                      0.006565                      {'Adab...   
6          31                      0.007171                      {'Adab...   
18         12                      0.002524                      {'Adab...   
13         24                      0.002727                      {'Adab...   
12         13                      0.005555                      {'Adab...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
8   -0.298067          -0.988626          -0.334729          -0.540474         
14  -0.305832          -0.984763          -0.337236          -0.542610         
0   -0.303364          -0.989754          -0.336898          -0.543338         
1   -0.313737          -0.984364          -0.336959          -0.545020         
15  -0.310967          -0.983993          -0.340489          -0.545149         
5   -0.313009          -0.983869          -0.339669          -0.545516         
10  -0.305638          -0.987006          -0.344950          -0.545865         
2   -0.310052          -0.984430          -0.343464          -0.545982         
4   -0.310952          -0.982536          -0.345853          -0.546447         
17  -0.310433          -0.987165          -0.342375          -0.546658         
3   -0.310583          -0.988169          -0.341344     

In [59]:
adaboost_search.best_params_

{'Adaboost__n_estimators': 50,
 'Adaboost__learning_rate': 0.0003020408163265306}

In [60]:
best_adaboost_model = adaboost_search.best_estimator_

In [64]:
y_pred = best_adaboost_model.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.7801460746969361

In [72]:
y_pred = best_adaboost_model.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.9476350970502071

In [65]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([524, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_adaboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.5402321])

In [67]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = best_adaboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.53098968])

In [68]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_adaboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.29225286])

In [69]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = best_adaboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.30835721])

In [70]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = best_adaboost_model.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.84948742])

## Gradientboost

In [74]:
from sklearn.ensemble import GradientBoostingRegressor

gradientboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('Gradientboost', GradientBoostingRegressor(random_state=42)),
    ])

param_distribs = {
    'Gradientboost__n_estimators': np.arange(10, 100),
    'Gradientboost__max_depth': np.arange(4, 20),
    'Gradientboost__learning_rate': np.linspace(1e-4, 1e-2),
}

gradientboost_search = RandomizedSearchCV(
    gradientboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


gradientboost_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('Gradientboost',
                                              GradientBoostingRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'Gradientboost__learning_rate': array([0.0001    , 0.00030204, 0.00050408, 0.00070612, 0.00090816,
       0.0011102 , 0.00131224, 0.00151429, 0.00171633, 0.00191837,
       0.00212041, 0.0023...
                                        'Gradientboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [75]:
pd.set_option('display.max_colwidth', 10)
gradientboost_search.cv_results_ = pd.DataFrame(gradientboost_search.cv_results_)
gradientboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
9    0.371470       0.049335      0.005000         0.002102        
2    0.234722       0.011463      0.005431         0.002341        
12   0.321308       0.030477      0.005597         0.004030        
17   0.345145       0.050442      0.009397         0.002594        
6    0.257644       0.032795      0.005777         0.003567        
13   0.238565       0.045105      0.005477         0.003511        
14   0.114075       0.027273      0.003083         0.000749        
8    0.331856       0.026348      0.006322         0.002633        
18   0.451245       0.081964      0.007587         0.004526        
19   0.088082       0.016265      0.002222         0.000409        
15   0.122162       0.034291      0.004987         0.002161        
10   0.096689       0.010564      0.007791         0.003022        
5    0.214378       0.017849      0.002569         0.000522        
4    0.128432       0.027978      0.003063         0.001405        
0    0.138343       0.008579      0.003472         0.000776        
3    0.244662       0.017442      0.003304         0.000946        
7    0.065980       0.009741      0.005152         0.002876        
16   0.036655       0.005010      0.003270         0.000102        
1    0.172880       0.018041      0.005729         0.002094        
11   0.258070       0.024840      0.006990         0.005872        

    param_Gradientboost__n_estimators  param_Gradientboost__max_depth  \
9          91                                 14                        
2          86                                  5                        
12         75                                 11                        
17         77                                  8                        
6          63                                 17                        
13         55                                 15                        
14         45                                  5                        
8          60                                 12                        
18         83                                 18                        
19         32                                 19                        
15         29                                  7                        
10         30                                  4                        
5          41                                 14                        
4          34                                 17                        
0          55                                 19                        
3          65                                  9                        
7          13                                  6                        
16         11                                 15                        
1          60                                 13                        
11         59                                 12                        

    param_Gradientboost__learning_rate     params  split0_test_score  \
9    0.009394                           {'Grad...  -0.376148           
2    0.007778                           {'Grad...  -0.410306           
12   0.008384                           {'Grad...  -0.412263           
17   0.007576                           {'Grad...  -0.422652           
6    0.008384                           {'Grad...  -0.443143           
13   0.008788                           {'Grad...  -0.456971           
14   0.009192                           {'Grad...  -0.486049           
8    0.005757                           {'Grad...  -0.507299           
18   0.003939                           {'Grad...  -0.514310           
19   0.010000                           {'Grad...  -0.518151           
15   0.009596                           {'Grad...  -0.534726           
10   0.009192                           {'Grad...  -0.547177           
5    0.006161                           {'Grad...  -0.548454           
4    0.005151                    

In [76]:
gradientboost_search.best_params_

{'Gradientboost__n_estimators': 91,
 'Gradientboost__max_depth': 14,
 'Gradientboost__learning_rate': 0.009393877551020408}

In [77]:
best_gradientboost_model = gradientboost_search.best_estimator_

In [78]:
y_pred = best_gradientboost_model.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.9742550622403962

In [79]:
y_pred = best_gradientboost_model.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

1.0724951889846688

In [80]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([524, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_gradientboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.06706534])

In [81]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = best_gradientboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.08312472])

In [82]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_gradientboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.68548991])

In [83]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = best_gradientboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.92948888])

In [84]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = best_gradientboost_model.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.71355435])

## xgboost

In [85]:
import xgboost as xgb

xgboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('xgboost', xgb.XGBRegressor(random_state=42)),
    ])

param_distribs = {
    'xgboost__n_estimators': np.arange(10, 100),
    'xgboost__max_depth': np.arange(4, 20),
}

xgboost_search = RandomizedSearchCV(
    xgboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


xgboost_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('xgboost',
                                              XGBRegressor(base_score=None,
                                                           booster=None,
                                                           callbacks=None,
                                                           colsample_bylevel=None,
                                                           colsample_bynode=None,
                                                           colsample_bytree=None,
                                                           device=None,
                                                           early_stopping_rounds=None,
                                                           enable_categorical=False,
                                                           eval_metric=None,
                                                           feature_types=None,
                                                           gamma=None,
                                                           grow_policy=None,
                                                           i...
                                        'xgboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [86]:
pd.set_option('display.max_colwidth', 10)
xgboost_search.cv_results_ = pd.DataFrame(xgboost_search.cv_results_)
xgboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
19   0.055043       0.012964      0.003769         0.000882        
18   0.054520       0.002519      0.004770         0.000954        
13   0.069686       0.002781      0.004545         0.000974        
5    0.075515       0.002197      0.005233         0.001072        
8    0.070862       0.007826      0.004407         0.001216        
6    0.081783       0.016965      0.008199         0.003287        
15   0.069150       0.003844      0.004923         0.000905        
12   0.074376       0.004871      0.006957         0.001225        
7    0.078434       0.001379      0.007007         0.001584        
17   0.080781       0.010024      0.004853         0.000744        
10   0.070947       0.006362      0.004653         0.000361        
1    0.080024       0.011686      0.008435         0.001722        
4    0.084218       0.012939      0.003870         0.000092        
2    0.049153       0.008987      0.004980         0.000580        
16   0.087959       0.013357      0.005493         0.001755        
3    0.053591       0.004029      0.005237         0.000634        
11   0.034433       0.002155      0.004944         0.000104        
0    0.097104       0.024384      0.006061         0.000536        
14   0.064053       0.016173      0.004898         0.001365        
9    0.057827       0.001636      0.004364         0.000519        

    param_xgboost__n_estimators  param_xgboost__max_depth     params  \
19         90                            7                 {'xgbo...   
18         46                            7                 {'xgbo...   
13         50                           14                 {'xgbo...   
5          74                           14                 {'xgbo...   
8          39                           17                 {'xgbo...   
6          50                           19                 {'xgbo...   
15         55                           18                 {'xgbo...   
12         63                           17                 {'xgbo...   
7          82                           19                 {'xgbo...   
17         46                           12                 {'xgbo...   
10         59                           10                 {'xgbo...   
1          75                           10                 {'xgbo...   
4          98                           10                 {'xgbo...   
2          18                           10                 {'xgbo...   
16         75                           11                 {'xgbo...   
3          75                            4                 {'xgbo...   
11         35                            5                 {'xgbo...   
0          88                            5                 {'xgbo...   
14         61                            5                 {'xgbo...   
9          74                            6                 {'xgbo...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
19  -0.282672          -0.967799          -0.334520          -0.528331         
18  -0.282656          -0.967799          -0.334537          -0.528331         
13  -0.299342          -0.972814          -0.332346          -0.534834         
5   -0.299366          -0.972814          -0.332342          -0.534841         
8   -0.299476          -0.972820          -0.332380          -0.534892         
6   -0.299523          -0.972814          -0.332346          -0.534895         
15  -0.299545          -0.972814          -0.332342          -0.534900         
12  -0.299545          -0.972814          -0.332342          -0.534900         
7   -0.299545          -0.972814          -0.332342          -0.534900         
17  -0.299305          -0.972814          -0.333221          -0.535113         
10  -0.302749          -0.972774          -0.333836          -0.536453         
1   -0.302749          -0.972774          -0.333836          -0.536453         
4   -0.302749         

In [87]:
xgboost_search.best_params_

{'xgboost__n_estimators': 90, 'xgboost__max_depth': 7}

In [88]:
best_xgboost_model = xgboost_search.best_estimator_

In [89]:
y_pred = best_xgboost_model.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.0025976832793214353

In [90]:
y_pred = best_xgboost_model.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.9208960388005969

In [91]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([524, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_xgboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([8.252278], dtype=float32)

In [92]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = best_xgboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([5.4272914], dtype=float32)

In [93]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_xgboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.1823974], dtype=float32)

In [94]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = best_xgboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.3462124], dtype=float32)

In [95]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = best_xgboost_model.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.4725465], dtype=float32)

## lightgbm

In [96]:
%pip install lightgbm

In [97]:
from lightgbm import LGBMRegressor

lightgbm_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('lightgbm', LGBMRegressor(random_state=42)),
    ])

param_distribs = {
    'lightgbm__n_estimators': np.arange(10, 100),
    'lightgbm__max_depth': np.arange(4, 20),
}

lightgbm_search = RandomizedSearchCV(
    lightgbm_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


lightgbm_search.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000126 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 442
[LightGBM] [Info] Number of data points in the train set: 152, number of used features: 11
[LightGBM] [Info] Start training from score 0.644009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, be

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('lightgbm',
                                              LGBMRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'lightgbm__max_depth': array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                                        'lightgbm__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [98]:
pd.set_option('display.max_colwidth', 10)
lightgbm_search.cv_results_ = pd.DataFrame(lightgbm_search.cv_results_)
lightgbm_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
11   0.060924       0.000861      0.019181         0.007296        
2    0.022893       0.019678      0.007999         0.004015        
8    0.054540       0.002765      0.015495         0.003005        
17   0.062485       0.012217      0.017420         0.011226        
18   0.047161       0.021100      0.013685         0.006742        
13   0.091809       0.014008      0.014875         0.010483        
6    0.047894       0.006014      0.010405         0.004075        
15   0.069510       0.038455      0.014708         0.008627        
12   0.086093       0.006329      0.020156         0.005796        
10   0.084503       0.001100      0.020032         0.008989        
14   0.057586       0.040618      0.015114         0.006422        
16   0.057779       0.039297      0.008121         0.002377        
3    0.057588       0.010669      0.014073         0.002798        
1    0.082172       0.019592      0.013377         0.006105        
5    0.047191       0.029262      0.010150         0.001521        
9    0.100708       0.010754      0.022486         0.001343        
7    0.068860       0.015285      0.016099         0.008268        
0    0.092266       0.025195      0.032611         0.006747        
19   0.046029       0.020700      0.008135         0.002823        
4    0.080164       0.021876      0.012763         0.001042        

    param_lightgbm__n_estimators  param_lightgbm__max_depth     params  \
11         35                             5                  {'ligh...   
2          18                            10                  {'ligh...   
8          39                            17                  {'ligh...   
17         46                            12                  {'ligh...   
18         46                             7                  {'ligh...   
13         50                            14                  {'ligh...   
6          50                            19                  {'ligh...   
15         55                            18                  {'ligh...   
12         63                            17                  {'ligh...   
10         59                            10                  {'ligh...   
14         61                             5                  {'ligh...   
16         75                            11                  {'ligh...   
3          75                             4                  {'ligh...   
1          75                            10                  {'ligh...   
5          74                            14                  {'ligh...   
9          74                             6                  {'ligh...   
7          82                            19                  {'ligh...   
0          88                             5                  {'ligh...   
19         90                             7                  {'ligh...   
4          98                            10                  {'ligh...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
11  -0.305881          -1.009656          -0.335553          -0.550363         
2   -0.280133          -1.031269          -0.345947          -0.552450         
8   -0.312079          -1.009085          -0.338217          -0.553127         
17  -0.317787          -1.008799          -0.337541          -0.554709         
18  -0.317787          -1.008799          -0.337541          -0.554709         
13  -0.320559          -1.009161          -0.337302          -0.555674         
6   -0.320559          -1.009161          -0.337302          -0.555674         
15  -0.322637          -1.009332          -0.338013          -0.556661         
12  -0.324179          -1.009764          -0.337869          -0.557271         
10  -0.323160          -1.009393          -0.339295          -0.557283         
14  -0.324481          -1.009707          -0.338042          -0.557410         
16  -0.325107          -1.011416          -0.338167         

In [99]:
lightgbm_search.best_params_

{'lightgbm__n_estimators': 35, 'lightgbm__max_depth': 5}

In [100]:
best_lightgbm_model = lightgbm_search.best_estimator_

In [101]:
y_pred = best_lightgbm_model.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.5968350219110156

In [102]:
y_pred = best_lightgbm_model.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.7813401824138744

In [103]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([524, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_lightgbm_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([4.44356748])

In [104]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = best_lightgbm_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([4.4871861])

In [105]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_lightgbm_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.72821165])

In [106]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = best_lightgbm_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.63276198])

In [107]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = best_lightgbm_model.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.87049048])

## catboost

In [108]:
%pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 5.5 MB/s eta 0:00:00


In [109]:
from catboost import CatBoostRegressor as Catboost

catboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('catboost', Catboost(random_state=42)),
    ])

param_distribs = {
    'catboost__n_estimators': np.arange(10, 100),
    'catboost__max_depth': np.arange(4, 20),
}

catboost_search = RandomizedSearchCV(
    catboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


catboost_search.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
15 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/usr/local/lib/pyth

Learning rate set to 0.215334
0:	learn: 0.8379678	total: 55.1ms	remaining: 4.9s
1:	learn: 0.7609917	total: 62.4ms	remaining: 2.74s
2:	learn: 0.7024511	total: 69.3ms	remaining: 2.01s
3:	learn: 0.6570651	total: 72.6ms	remaining: 1.56s
4:	learn: 0.6312244	total: 77.6ms	remaining: 1.32s
5:	learn: 0.6089074	total: 81.3ms	remaining: 1.14s
6:	learn: 0.5884607	total: 85.3ms	remaining: 1.01s
7:	learn: 0.5588328	total: 92ms	remaining: 943ms
8:	learn: 0.5407704	total: 96.2ms	remaining: 866ms
9:	learn: 0.5039799	total: 100ms	remaining: 803ms
10:	learn: 0.4752397	total: 102ms	remaining: 734ms
11:	learn: 0.4623382	total: 103ms	remaining: 668ms
12:	learn: 0.4446557	total: 105ms	remaining: 623ms
13:	learn: 0.4310252	total: 110ms	remaining: 595ms
14:	learn: 0.4138502	total: 115ms	remaining: 575ms
15:	learn: 0.3923775	total: 120ms	remaining: 557ms
16:	learn: 0.3812194	total: 125ms	remaining: 536ms
17:	learn: 0.3695018	total: 128ms	remaining: 512ms
18:	learn: 0.3611609	total: 131ms	remaining: 491ms
19:	l

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('catboost',
                                              <catboost.core.CatBoostRegressor object at 0x7bebc704b610>)]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'catboost__max_depth': array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                                        'catboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [110]:
pd.set_option('display.max_colwidth', 10)
catboost_search.cv_results_ = pd.DataFrame(catboost_search.cv_results_)
catboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
19   0.621295       0.174729      0.013197         0.004557        
0    0.274980       0.053393      0.008943         0.000751        
18   0.376230       0.020148      0.009646         0.005339        
3    1.372822       0.382400      0.019601         0.013049        
11   0.122707       0.016313      0.007749         0.002287        
14   0.199263       0.032768      0.007346         0.001987        
16   2.327398       0.123996      0.005983         0.000303        
9    0.657902       0.093802      0.010650         0.002779        
4    4.737945       1.148594      0.015835         0.007715        
1    5.065350       0.622023      0.016260         0.003235        
10   1.574391       0.163319      0.013649         0.006697        
2    1.150581       0.143916      0.017815         0.008837        
5   34.375699       6.782910      0.018559         0.007898        
17   3.325588       0.661696      0.013438         0.004228        
13  17.712349       4.229952      0.007440         0.002128        
7    0.029911       0.003762      0.000000         0.000000        
12   0.010200       0.002962      0.000000         0.000000        
6    0.029093       0.004683      0.000000         0.000000        
15   0.007732       0.001780      0.000000         0.000000        
8    0.036253       0.000239      0.000000         0.000000        

    param_catboost__n_estimators  param_catboost__max_depth     params  \
19         90                             7                  {'catb...   
0          88                             5                  {'catb...   
18         46                             7                  {'catb...   
3          75                             4                  {'catb...   
11         35                             5                  {'catb...   
14         61                             5                  {'catb...   
16         75                            11                  {'catb...   
9          74                             6                  {'catb...   
4          98                            10                  {'catb...   
1          75                            10                  {'catb...   
10         59                            10                  {'catb...   
2          18                            10                  {'catb...   
5          74                            14                  {'catb...   
17         46                            12                  {'catb...   
13         50                            14                  {'catb...   
7          82                            19                  {'catb...   
12         63                            17                  {'catb...   
6          50                            19                  {'catb...   
15         55                            18                  {'catb...   
8          39                            17                  {'catb...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
19  -0.271027          -0.972788          -0.313841          -0.519219         
0   -0.266508          -0.981199          -0.324236          -0.523981         
18  -0.266589          -0.975622          -0.334143          -0.525452         
3   -0.276996          -0.991370          -0.317323          -0.528563         
11  -0.302986          -0.967321          -0.321613          -0.530640         
14  -0.271326          -0.976040          -0.351960          -0.533109         
16  -0.286869          -0.979864          -0.342585          -0.536439         
9   -0.284033          -0.977939          -0.351649          -0.537874         
4   -0.284546          -0.992042          -0.343130          -0.539906         
1   -0.290046          -0.987913          -0.345147          -0.541035         
10  -0.291103          -0.991730          -0.347055          -0.543296         
2   -0.320115          -0.990018          -0.327315         

In [111]:
catboost_search.best_params_

{'catboost__n_estimators': 90, 'catboost__max_depth': 7}

In [112]:
best_catboost_model = catboost_search.best_estimator_

In [113]:
y_pred = best_catboost_model.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.1748032793685214

In [114]:
y_pred = best_catboost_model.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.7647288101444115

In [115]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([524, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_catboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.69694534])

In [116]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = best_catboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([4.63091603])

In [117]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_catboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.69681995])

In [118]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = best_catboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.80705903])

In [119]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = best_catboost_model.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.11949409])