In [1]:
%pip install "scikit-learn<1.6"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 15.3 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.0
    Uninstalling scikit-learn-1.6.0:
      Successfully uninstalled scikit-learn-1.6.0


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv('/content/sample_data/final_df.csv', index_col=0)

In [27]:
# Split train and test
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

# split features and labels
X_train = train_set.drop("WAR", axis=1).to_numpy()
y_train = train_set["WAR"].copy().to_numpy()
X_test = test_set.drop("WAR", axis=1).to_numpy()
y_test = test_set["WAR"].copy().to_numpy()

## NonLinear SVM

In [28]:
from sklearn.metrics import mean_squared_error, make_scorer
scorer = make_scorer(mean_squared_error, greater_is_better=False, squared=False)

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RandomizedSearchCV


svm_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ("SVR", SVR(kernel='poly')),
    ])

param_distribs = {'SVR__degree': np.arange(2, 11),
                  'SVR__C': np.linspace(0.01, 0.1, 10),
                  'SVR__epsilon': np.linspace(0.01, 0.1, 10),
                  }

svm_search = RandomizedSearchCV(
    svm_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


svm_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('SVR', SVR(kernel='poly'))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'SVR__C': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ]),
                                        'SVR__degree': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
                                        'SVR__epsilon': array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [30]:
pd.set_option('display.max_colwidth', 10)
svm_search.cv_results_ = pd.DataFrame(svm_search.cv_results_)
svm_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
5    0.008902       0.004480      0.004442         0.001292        
1    0.004577       0.001130      0.003897         0.000934        
6    0.007613       0.001576      0.003527         0.000457        
7    0.006140       0.000608      0.003178         0.000558        
4    0.006989       0.004538      0.003288         0.000708        
13   0.003921       0.000136      0.002271         0.000039        
10   0.008229       0.004493      0.003209         0.000176        
3    0.009691       0.004800      0.004857         0.002719        
2    0.011012       0.004297      0.003304         0.000215        
17   0.018875       0.017338      0.002332         0.000792        
15   0.012029       0.002205      0.003312         0.001166        
19   0.004248       0.000721      0.001163         0.000051        
16   0.020451       0.009181      0.002275         0.000131        
8    0.010251       0.001464      0.002924         0.001874        
0    0.010874       0.002275      0.002647         0.000613        
9    0.029291       0.027372      0.002815         0.000972        
18   0.052488       0.050376      0.001562         0.000210        
11   0.087655       0.065076      0.002784         0.000403        
14   0.081027       0.053724      0.002941         0.000197        
12   0.091571       0.063480      0.002192         0.000426        

    param_SVR__epsilon  param_SVR__degree  param_SVR__C     params  \
5        0.02                   3               0.09     {'SVR_...   
1        0.08                   3               0.10     {'SVR_...   
6        0.10                   4               0.04     {'SVR_...   
7        0.01                   4               0.02     {'SVR_...   
4        0.10                   5               0.01     {'SVR_...   
13       0.01                   5               0.02     {'SVR_...   
10       0.10                   6               0.02     {'SVR_...   
3        0.09                   6               0.07     {'SVR_...   
2        0.02                   7               0.03     {'SVR_...   
17       0.03                   8               0.05     {'SVR_...   
15       0.01                   7               0.07     {'SVR_...   
19       0.08                   8               0.01     {'SVR_...   
16       0.09                   9               0.02     {'SVR_...   
8        0.03                   9               0.01     {'SVR_...   
0        0.01                   9               0.01     {'SVR_...   
9        0.07                  10               0.01     {'SVR_...   
18       0.08                  10               0.05     {'SVR_...   
11       0.04                  10               0.06     {'SVR_...   
14       0.02                  10               0.08     {'SVR_...   
12       0.02                  10               0.09     {'SVR_...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
5   -0.728530          -1.061496          -0.582076          -0.790701         
1   -0.772431          -1.053078          -0.580924          -0.802144         
6   -0.691769          -1.209716          -0.678354          -0.859946         
7   -0.699475          -1.224789          -0.689210          -0.871158         
4   -0.957968          -1.206923          -0.661499          -0.942130         
13  -0.942975          -1.222060          -0.671094          -0.945376         
10  -1.061825          -1.217858          -0.692150          -0.990611         
3   -1.378454          -1.278795          -0.738223          -1.131824         
2   -4.013151          -1.355875          -0.793901          -2.054309         
17  -3.206412          -1.685347          -1.463529          -2.118429         
15  -3.926620          -1.383984          -1.102803          -2.137802         
19  -4.790234          -1.402549          -0.765757          -2.319513         
16  -3.330787          -2.038870          -2.160924          -2.

In [31]:
svm_search.best_params_

{'SVR__epsilon': 0.020000000000000004,
 'SVR__degree': 3,
 'SVR__C': 0.09000000000000001}

In [32]:
best_svm_model = svm_search.best_estimator_

In [33]:
from sklearn.metrics import root_mean_squared_error
y_pred = best_svm_model.predict(X_train)
rmsle = root_mean_squared_error(y_train, y_pred)
rmsle

0.772957630205037

In [34]:
y_pred = best_svm_model.predict(X_test)
rmsle = root_mean_squared_error(y_test, y_pred)
rmsle

0.7615784540732059

In [35]:
# Chang-Ki Hong(6.67) 2023
ChangKiHong = np.array([np.log(109), np.log(65), np.log(216)])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_svm_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.94797459])

In [41]:
# Austin (4.97) 2023
Auntin = np.array([np.log(65), np.log(95), np.log(269)])
Auntin = Auntin.reshape(1, -1)
y_pred = best_svm_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.44419758])

In [39]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([np.log(62), np.log(49), np.log(168)])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_svm_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.17039867])

In [43]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([np.log(65), np.log(41), np.log(152)])
Choo = Choo.reshape(1, -1)
y_pred = best_svm_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.16200567])

In [44]:
# Jae-Hwan Kim (0.44) 2023
JaeHwanKim = np.array([np.log(40), np.log(46), np.log(134)])
JaeHwanKim = JaeHwanKim.reshape(1, -1)
y_pred = best_svm_model.predict(JaeHwanKim)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.97223634])

## RandomForest

In [46]:
from sklearn.ensemble import RandomForestRegressor

randomforest_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('RandomForest', RandomForestRegressor(random_state=42)),
    ])

param_distribs = {
    'RandomForest__n_estimators': np.arange(10, 100),
    'RandomForest__max_depth': np.arange(4, 20),
}

randomforest_search = RandomizedSearchCV(
    randomforest_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


randomforest_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('RandomForest',
                                              RandomForestRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'RandomForest__max_depth': array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                                        'RandomForest__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [47]:
pd.set_option('display.max_colwidth', 10)
randomforest_search.cv_results_ = pd.DataFrame(randomforest_search.cv_results_)
randomforest_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
11   0.145102       0.007782      0.014606         0.006968        
3    0.297695       0.074937      0.011619         0.004435        
14   0.136692       0.008236      0.006650         0.000216        
0    0.298448       0.069218      0.016286         0.005287        
9    0.326875       0.014113      0.018855         0.004257        
1    0.436939       0.025195      0.017688         0.002827        
10   0.252496       0.005850      0.012999         0.001540        
16   0.169240       0.011088      0.008385         0.000035        
5    0.295856       0.031048      0.014085         0.002536        
8    0.173567       0.008422      0.014207         0.001976        
12   0.271732       0.005356      0.018583         0.003662        
7    0.302844       0.029861      0.018717         0.002158        
18   0.105870       0.008514      0.005536         0.000442        
19   0.181170       0.018107      0.007672         0.001611        
15   0.119456       0.002045      0.007734         0.001948        
6    0.174591       0.045169      0.009446         0.001709        
13   0.212235       0.008615      0.011430         0.004422        
17   0.103836       0.004366      0.005946         0.000262        
4    0.404391       0.036474      0.014484         0.004741        
2    0.087857       0.006910      0.007831         0.004251        

    param_RandomForest__n_estimators  param_RandomForest__max_depth  \
11         35                                 5                       
3          75                                 4                       
14         61                                 5                       
0          88                                 5                       
9          74                                 6                       
1          75                                10                       
10         59                                10                       
16         75                                11                       
5          74                                14                       
8          39                                17                       
12         63                                17                       
7          82                                19                       
18         46                                 7                       
19         90                                 7                       
15         55                                18                       
6          50                                19                       
13         50                                14                       
17         46                                12                       
4          98                                10                       
2          18                                10                       

       params  split0_test_score  split1_test_score  split2_test_score  \
11  {'Rand...  -0.488279          -1.069157          -0.577023           
3   {'Rand...  -0.524028          -1.054902          -0.556247           
14  {'Rand...  -0.517221          -1.061649          -0.572766           
0   {'Rand...  -0.535934          -1.060068          -0.568518           
9   {'Rand...  -0.536391          -1.059244          -0.570884           
1   {'Rand...  -0.541610          -1.061862          -0.570809           
10  {'Rand...  -0.524283          -1.066746          -0.583253           
16  {'Rand...  -0.539861          -1.060916          -0.573539           
5   {'Rand...  -0.542887          -1.060566          -0.574014           
8   {'Rand...  -0.510305          -1.072222          -0.601206           
12  {'Rand...  -0.537775          -1.063673          -0.582506           
7   {'Rand...  -0.542468          -1.060848          -0.581481           
18  {'Rand...  -0.507398          -1.067893          -0.611005           
19  {'Rand...  -0.548225          -1.061925    

In [48]:
randomforest_search.best_params_

{'RandomForest__n_estimators': 35, 'RandomForest__max_depth': 5}

In [49]:
best_randomforest_model = randomforest_search.best_estimator_

In [50]:
y_pred = best_randomforest_model.predict(X_train)
rmsle = root_mean_squared_error(y_train, y_pred)
rmsle

0.3376841906106003

In [51]:
y_pred = best_randomforest_model.predict(X_test)
rmsle = root_mean_squared_error(y_test, y_pred)
rmsle

1.4781144096168983

In [52]:
# Chang-Ki Hong(6.67) 2023
ChangKiHong = np.array([np.log(109), np.log(65), np.log(216)])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_randomforest_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.24896176])

In [53]:
# Austin (4.97) 2023
Auntin = np.array([np.log(65), np.log(95), np.log(269)])
Auntin = Auntin.reshape(1, -1)
y_pred = best_randomforest_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.57359769])

In [54]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([np.log(62), np.log(49), np.log(168)])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_randomforest_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.59414944])

In [55]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([np.log(65), np.log(41), np.log(152)])
Choo = Choo.reshape(1, -1)
y_pred = best_randomforest_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.94486647])

In [56]:
# Jae-Hwan Kim (0.44) 2023
JaeHwanKim = np.array([np.log(40), np.log(46), np.log(134)])
JaeHwanKim = JaeHwanKim.reshape(1, -1)
y_pred = best_randomforest_model.predict(JaeHwanKim)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.51621439])

## Adaboost

In [58]:
from sklearn.ensemble import AdaBoostRegressor

adaboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('Adaboost', AdaBoostRegressor(random_state=42)),
    ])

param_distribs = {
    'Adaboost__n_estimators': np.arange(10, 100),
    'Adaboost__learning_rate': np.linspace(1e-4, 1e-2),
}

adaboost_search = RandomizedSearchCV(
    adaboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


adaboost_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('Adaboost',
                                              AdaBoostRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'Adaboost__learning_rate': array([0.0001    , 0.00030204, 0.00050408, 0.00070612, 0.00090816,
       0.0011102 , 0.00131224, 0.00151429, 0.00171633, 0.00191837,
       0.00212041, 0.00232245, 0.00252449, 0....
                                        'Adaboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [59]:
pd.set_option('display.max_colwidth', 10)
adaboost_search.cv_results_ = pd.DataFrame(adaboost_search.cv_results_)
adaboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
12   0.072926       0.033510      0.013601         0.001589        
18   0.127657       0.050414      0.021379         0.002882        
4    0.096007       0.025666      0.009382         0.003134        
0    0.220835       0.056163      0.028462         0.009251        
3    0.088064       0.022158      0.008538         0.000437        
19   0.172336       0.043249      0.016401         0.007699        
9    0.186710       0.008526      0.018340         0.000922        
10   0.145423       0.000649      0.014963         0.000519        
14   0.228327       0.052495      0.021703         0.006158        
13   0.108280       0.015418      0.010501         0.004796        
7    0.126805       0.016251      0.013297         0.000711        
8    0.121396       0.000690      0.013002         0.000267        
1    0.338121       0.084408      0.042627         0.017139        
15   0.540746       0.141266      0.042286         0.004332        
5    0.080741       0.000587      0.009214         0.000696        
16   0.293598       0.069547      0.025997         0.007469        
2    0.145417       0.032486      0.015955         0.004537        
17   0.226913       0.069744      0.031515         0.019921        
11   0.194353       0.054260      0.026088         0.007781        
6    0.074759       0.000480      0.009492         0.000647        

    param_Adaboost__n_estimators  param_Adaboost__learning_rate     params  \
12         13                      0.005555                      {'Adab...   
18         12                      0.002524                      {'Adab...   
4          26                      0.010000                      {'Adab...   
0          60                      0.001918                      {'Adab...   
3          26                      0.001110                      {'Adab...   
19         48                      0.005757                      {'Adab...   
9          75                      0.003737                      {'Adab...   
10         59                      0.001716                      {'Adab...   
14         65                      0.007576                      {'Adab...   
13         24                      0.002727                      {'Adab...   
7          49                      0.006565                      {'Adab...   
8          50                      0.000302                      {'Adab...   
1          92                      0.008384                      {'Adab...   
15         77                      0.009192                      {'Adab...   
5          34                      0.007778                      {'Adab...   
16         34                      0.006565                      {'Adab...   
2          42                      0.006969                      {'Adab...   
17         34                      0.001110                      {'Adab...   
11         61                      0.005353                      {'Adab...   
6          31                      0.007171                      {'Adab...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
12  -0.385392          -1.090660          -0.449627          -0.641893         
18  -0.390735          -1.084514          -0.450685          -0.641978         
4   -0.382203          -1.082497          -0.467633          -0.644111         
0   -0.382054          -1.080412          -0.471071          -0.644512         
3   -0.385687          -1.084454          -0.467834          -0.645992         
19  -0.385924          -1.082082          -0.470031          -0.646013         
9   -0.381174          -1.082129          -0.475076          -0.646126         
10  -0.384203          -1.082348          -0.472175          -0.646242         
14  -0.382971          -1.080281          -0.475500          -0.646251         
13  -0.385386          -1.085297          -0.468419          -0.646367         
7   -0.383153          -1.082231          -0.473724     

In [60]:
adaboost_search.best_params_

{'Adaboost__n_estimators': 13, 'Adaboost__learning_rate': 0.005555102040816327}

In [61]:
best_adaboost_model = adaboost_search.best_estimator_

In [62]:
y_pred = best_adaboost_model.predict(X_train)
rmsle = root_mean_squared_error(y_train, y_pred)
rmsle

0.6473108557225109

In [63]:
y_pred = best_adaboost_model.predict(X_test)
rmsle = root_mean_squared_error(y_test, y_pred)
rmsle

0.3339275177043217

In [64]:
# Chang-Ki Hong(6.67) 2023
ChangKiHong = np.array([np.log(109), np.log(65), np.log(216)])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_adaboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.897678])

In [65]:
# Austin (4.97) 2023
Auntin = np.array([np.log(65), np.log(95), np.log(269)])
Auntin = Auntin.reshape(1, -1)
y_pred = best_adaboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.07421191])

In [66]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([np.log(62), np.log(49), np.log(168)])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_adaboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.63157333])

In [67]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([np.log(65), np.log(41), np.log(152)])
Choo = Choo.reshape(1, -1)
y_pred = best_adaboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.66085333])

In [68]:
# Jae-Hwan Kim (0.44) 2023
JaeHwanKim = np.array([np.log(40), np.log(46), np.log(134)])
JaeHwanKim = JaeHwanKim.reshape(1, -1)
y_pred = best_adaboost_model.predict(JaeHwanKim)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.56071351])

## Gradientboost

In [69]:
from sklearn.ensemble import GradientBoostingRegressor

gradientboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('Gradientboost', GradientBoostingRegressor(random_state=42)),
    ])

param_distribs = {
    'Gradientboost__n_estimators': np.arange(10, 100),
    'Gradientboost__max_depth': np.arange(4, 20),
    'Gradientboost__learning_rate': np.linspace(1e-4, 1e-2),
}

gradientboost_search = RandomizedSearchCV(
    gradientboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


gradientboost_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('Gradientboost',
                                              GradientBoostingRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'Gradientboost__learning_rate': array([0.0001    , 0.00030204, 0.00050408, 0.00070612, 0.00090816,
       0.0011102 , 0.00131224, 0.00151429, 0.00171633, 0.00191837,
       0.00212041, 0.0023...
                                        'Gradientboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [70]:
pd.set_option('display.max_colwidth', 10)
gradientboost_search.cv_results_ = pd.DataFrame(gradientboost_search.cv_results_)
gradientboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
2    0.184843       0.003028      0.008742         0.004361        
9    0.140274       0.012760      0.005013         0.003023        
17   0.098148       0.003837      0.003253         0.000532        
12   0.098889       0.002872      0.002476         0.000481        
6    0.165163       0.015103      0.003919         0.000335        
13   0.074883       0.000080      0.002391         0.000429        
14   0.075568       0.007126      0.002825         0.000804        
8    0.126269       0.020265      0.003189         0.001148        
18   0.124982       0.009001      0.004511         0.001305        
19   0.051432       0.017670      0.002254         0.000515        
15   0.042162       0.004912      0.002061         0.000235        
10   0.037046       0.006125      0.002951         0.000822        
5    0.092583       0.032825      0.009094         0.004290        
4    0.096013       0.008473      0.004643         0.002970        
0    0.163408       0.017629      0.008362         0.003776        
3    0.161294       0.008703      0.013697         0.001741        
7    0.035021       0.004744      0.003329         0.000298        
16   0.017715       0.000263      0.002967         0.000140        
1    0.157935       0.005272      0.008442         0.004556        
11   0.099728       0.024769      0.004770         0.002340        

    param_Gradientboost__n_estimators  param_Gradientboost__max_depth  \
2          86                                  5                        
9          91                                 14                        
17         77                                  8                        
12         75                                 11                        
6          63                                 17                        
13         55                                 15                        
14         45                                  5                        
8          60                                 12                        
18         83                                 18                        
19         32                                 19                        
15         29                                  7                        
10         30                                  4                        
5          41                                 14                        
4          34                                 17                        
0          55                                 19                        
3          65                                  9                        
7          13                                  6                        
16         11                                 15                        
1          60                                 13                        
11         59                                 12                        

    param_Gradientboost__learning_rate     params  split0_test_score  \
2    0.007778                           {'Grad...  -0.485939           
9    0.009394                           {'Grad...  -0.494246           
17   0.007576                           {'Grad...  -0.508856           
12   0.008384                           {'Grad...  -0.514598           
6    0.008384                           {'Grad...  -0.528281           
13   0.008788                           {'Grad...  -0.536678           
14   0.009192                           {'Grad...  -0.542704           
8    0.005757                           {'Grad...  -0.565632           
18   0.003939                           {'Grad...  -0.572024           
19   0.010000                           {'Grad...  -0.572504           
15   0.009596                           {'Grad...  -0.582810           
10   0.009192                           {'Grad...  -0.582984           
5    0.006161                           {'Grad...  -0.591548           
4    0.005151                    

In [71]:
gradientboost_search.best_params_

{'Gradientboost__n_estimators': 86,
 'Gradientboost__max_depth': 5,
 'Gradientboost__learning_rate': 0.0077775510204081645}

In [72]:
best_gradientboost_model = gradientboost_search.best_estimator_

In [73]:
y_pred = best_gradientboost_model.predict(X_train)
rmsle = root_mean_squared_error(y_train, y_pred)
rmsle

0.5317335928106108

In [74]:
y_pred = best_gradientboost_model.predict(X_test)
rmsle = root_mean_squared_error(y_test, y_pred)
rmsle

0.9828252676490122

In [75]:
# Chang-Ki Hong(6.67) 2023
ChangKiHong = np.array([np.log(109), np.log(65), np.log(216)])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_gradientboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.55721309])

In [77]:
# Austin (4.97) 2023
Auntin = np.array([np.log(65), np.log(95), np.log(269)])
Auntin = Auntin.reshape(1, -1)
y_pred = best_gradientboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.09899725])

In [78]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([np.log(62), np.log(49), np.log(168)])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_gradientboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.21983976])

In [79]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([np.log(65), np.log(41), np.log(152)])
Choo = Choo.reshape(1, -1)
y_pred = best_gradientboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.39727344])

In [80]:
# Jae-Hwan Kim (0.44) 2023
JaeHwanKim = np.array([np.log(40), np.log(46), np.log(134)])
JaeHwanKim = JaeHwanKim.reshape(1, -1)
y_pred = best_gradientboost_model.predict(JaeHwanKim)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.55638003])

## xgboost

In [81]:
import xgboost as xgb

xgboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('xgboost', xgb.XGBRegressor(random_state=42)),
    ])

param_distribs = {
    'xgboost__n_estimators': np.arange(10, 100),
    'xgboost__max_depth': np.arange(4, 20),
}

xgboost_search = RandomizedSearchCV(
    xgboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


xgboost_search.fit(X_train, y_train)

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('xgboost',
                                              XGBRegressor(base_score=None,
                                                           booster=None,
                                                           callbacks=None,
                                                           colsample_bylevel=None,
                                                           colsample_bynode=None,
                                                           colsample_bytree=None,
                                                           device=None,
                                                           early_stopping_rounds=None,
                                                           enable_categorical=False,
                                                           eval_metric=None,
                                                           feature_types=None,
                                                           gamma=None,
                                                           grow_policy=None,
                                                           i...
                                        'xgboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [82]:
pd.set_option('display.max_colwidth', 10)
xgboost_search.cv_results_ = pd.DataFrame(xgboost_search.cv_results_)
xgboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
3    0.031797       0.000500      0.003799         0.000750        
11   0.023335       0.000788      0.004646         0.000349        
5    0.057854       0.005094      0.003980         0.000507        
13   0.092044       0.030184      0.004707         0.001223        
6    0.049281       0.001346      0.003520         0.000190        
12   0.067162       0.022081      0.006596         0.003500        
7    0.052569       0.002780      0.003301         0.000248        
15   0.061253       0.016081      0.004845         0.000330        
8    0.045156       0.001288      0.005209         0.000407        
14   0.037043       0.007474      0.004925         0.000119        
17   0.057595       0.015235      0.004268         0.000835        
16   0.125718       0.027226      0.007385         0.004309        
1    0.050168       0.004104      0.004246         0.000856        
4    0.062451       0.014211      0.006461         0.001192        
10   0.051165       0.008400      0.005345         0.001880        
2    0.024967       0.001054      0.005174         0.000414        
18   0.048331       0.022661      0.003377         0.000126        
0    0.074803       0.021673      0.006748         0.004263        
19   0.054546       0.008783      0.003734         0.000200        
9    0.052854       0.005213      0.004968         0.000654        

    param_xgboost__n_estimators  param_xgboost__max_depth     params  \
3          75                            4                 {'xgbo...   
11         35                            5                 {'xgbo...   
5          74                           14                 {'xgbo...   
13         50                           14                 {'xgbo...   
6          50                           19                 {'xgbo...   
12         63                           17                 {'xgbo...   
7          82                           19                 {'xgbo...   
15         55                           18                 {'xgbo...   
8          39                           17                 {'xgbo...   
14         61                            5                 {'xgbo...   
17         46                           12                 {'xgbo...   
16         75                           11                 {'xgbo...   
1          75                           10                 {'xgbo...   
4          98                           10                 {'xgbo...   
10         59                           10                 {'xgbo...   
2          18                           10                 {'xgbo...   
18         46                            7                 {'xgbo...   
0          88                            5                 {'xgbo...   
19         90                            7                 {'xgbo...   
9          74                            6                 {'xgbo...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
3   -0.433684          -1.047199          -0.564588          -0.681824         
11  -0.443354          -1.054231          -0.554007          -0.683864         
5   -0.452999          -1.065410          -0.561866          -0.693425         
13  -0.452997          -1.065410          -0.561868          -0.693425         
6   -0.452997          -1.065230          -0.562373          -0.693534         
12  -0.452999          -1.065230          -0.562376          -0.693535         
7   -0.452999          -1.065230          -0.562376          -0.693535         
15  -0.452999          -1.065230          -0.562375          -0.693535         
8   -0.452999          -1.065300          -0.562387          -0.693562         
14  -0.455674          -1.056842          -0.569075          -0.693864         
17  -0.453034          -1.066008          -0.562879          -0.693974         
16  -0.455831          -1.060177          -0.566882          -0.694297         
1   -0.457259         

In [83]:
xgboost_search.best_params_

{'xgboost__n_estimators': 75, 'xgboost__max_depth': 4}

In [84]:
best_xgboost_model = xgboost_search.best_estimator_

In [85]:
y_pred = best_xgboost_model.predict(X_train)
rmsle = root_mean_squared_error(y_train, y_pred)
rmsle

0.06915987252816153

In [86]:
y_pred = best_xgboost_model.predict(X_test)
rmsle = root_mean_squared_error(y_test, y_pred)
rmsle

1.9943645964426153

In [87]:
# Chang-Ki Hong(6.67) 2023
ChangKiHong = np.array([np.log(109), np.log(65), np.log(216)])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_xgboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.2734656], dtype=float32)

In [88]:
# Austin (4.97) 2023
Auntin = np.array([np.log(65), np.log(95), np.log(269)])
Auntin = Auntin.reshape(1, -1)
y_pred = best_xgboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.5019624], dtype=float32)

In [89]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([np.log(62), np.log(49), np.log(168)])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_xgboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.639875], dtype=float32)

In [90]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([np.log(65), np.log(41), np.log(152)])
Choo = Choo.reshape(1, -1)
y_pred = best_xgboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.8394623], dtype=float32)

In [91]:
# Jae-Hwan Kim (0.44) 2023
JaeHwanKim = np.array([np.log(40), np.log(46), np.log(134)])
JaeHwanKim = JaeHwanKim.reshape(1, -1)
y_pred = best_xgboost_model.predict(JaeHwanKim)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.10930967], dtype=float32)

## lightgbm

In [92]:
%pip install lightgbm

In [93]:
from lightgbm import LGBMRegressor

lightgbm_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('lightgbm', LGBMRegressor(random_state=42)),
    ])

param_distribs = {
    'lightgbm__n_estimators': np.arange(10, 100),
    'lightgbm__max_depth': np.arange(4, 20),
}

lightgbm_search = RandomizedSearchCV(
    lightgbm_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


lightgbm_search.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000053 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 133
[LightGBM] [Info] Number of data points in the train set: 152, number of used features: 3
[LightGBM] [Info] Start training from score 0.644009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, bes

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('lightgbm',
                                              LGBMRegressor(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'lightgbm__max_depth': array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                                        'lightgbm__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [94]:
pd.set_option('display.max_colwidth', 10)
lightgbm_search.cv_results_ = pd.DataFrame(lightgbm_search.cv_results_)
lightgbm_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
2    0.015084       0.007138      0.003852         0.000801        
11   0.030586       0.026551      0.009250         0.008385        
8    0.019348       0.001680      0.005907         0.000767        
17   0.035455       0.008172      0.015438         0.004006        
18   0.049518       0.028404      0.011822         0.008989        
13   0.017074       0.004402      0.004802         0.001094        
6    0.014688       0.002653      0.003711         0.000080        
15   0.032712       0.023746      0.008244         0.008099        
10   0.069649       0.002757      0.015982         0.007321        
12   0.022890       0.010419      0.003650         0.000845        
14   0.017986       0.007474      0.003582         0.000797        
16   0.030785       0.009420      0.012569         0.006856        
3    0.035831       0.023227      0.006637         0.004630        
1    0.045445       0.006470      0.012636         0.004189        
5    0.038610       0.022963      0.004374         0.000808        
9    0.035727       0.003833      0.008136         0.004905        
7    0.046552       0.018828      0.017076         0.009645        
19   0.042708       0.012678      0.010302         0.002487        
0    0.045497       0.026675      0.005592         0.001587        
4    0.045640       0.027591      0.005189         0.001594        

    param_lightgbm__n_estimators  param_lightgbm__max_depth     params  \
2          18                            10                  {'ligh...   
11         35                             5                  {'ligh...   
8          39                            17                  {'ligh...   
17         46                            12                  {'ligh...   
18         46                             7                  {'ligh...   
13         50                            14                  {'ligh...   
6          50                            19                  {'ligh...   
15         55                            18                  {'ligh...   
10         59                            10                  {'ligh...   
12         63                            17                  {'ligh...   
14         61                             5                  {'ligh...   
16         75                            11                  {'ligh...   
3          75                             4                  {'ligh...   
1          75                            10                  {'ligh...   
5          74                            14                  {'ligh...   
9          74                             6                  {'ligh...   
7          82                            19                  {'ligh...   
19         90                             7                  {'ligh...   
0          88                             5                  {'ligh...   
4          98                            10                  {'ligh...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
2   -0.371338          -1.089593          -0.474003          -0.644978         
11  -0.384202          -1.074517          -0.488504          -0.649074         
8   -0.386425          -1.073613          -0.488706          -0.649581         
17  -0.390046          -1.073182          -0.490428          -0.651219         
18  -0.390046          -1.073182          -0.490428          -0.651219         
13  -0.391153          -1.074039          -0.491975          -0.652389         
6   -0.391153          -1.074039          -0.491975          -0.652389         
15  -0.392667          -1.074400          -0.491807          -0.652958         
10  -0.393707          -1.074729          -0.492885          -0.653774         
12  -0.396129          -1.074466          -0.492797          -0.654464         
14  -0.394769          -1.075375          -0.493867          -0.654671         
16  -0.399473          -1.074507          -0.493844         

In [95]:
lightgbm_search.best_params_

{'lightgbm__n_estimators': 18, 'lightgbm__max_depth': 10}

In [96]:
best_lightgbm_model = lightgbm_search.best_estimator_

In [97]:
y_pred = best_lightgbm_model.predict(X_train)
rmsle = root_mean_squared_error(y_train, y_pred)
rmsle

0.6735379612906522

In [98]:
y_pred = best_lightgbm_model.predict(X_test)
rmsle = root_mean_squared_error(y_test, y_pred)
rmsle

0.3068938521147489

In [99]:
# Chang-Ki Hong(6.67) 2023
ChangKiHong = np.array([np.log(109), np.log(65), np.log(216)])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_lightgbm_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.85164379])

In [100]:
# Austin (4.97) 2023
Auntin = np.array([np.log(65), np.log(95), np.log(269)])
Auntin = Auntin.reshape(1, -1)
y_pred = best_lightgbm_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.51093398])

In [101]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([np.log(62), np.log(49), np.log(168)])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_lightgbm_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.34126239])

In [102]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([np.log(65), np.log(41), np.log(152)])
Choo = Choo.reshape(1, -1)
y_pred = best_lightgbm_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.34126239])

In [103]:
# Jae-Hwan Kim (0.44) 2023
JaeHwanKim = np.array([np.log(40), np.log(46), np.log(134)])
JaeHwanKim = JaeHwanKim.reshape(1, -1)
y_pred = best_lightgbm_model.predict(JaeHwanKim)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.54057758])

## catboost

In [104]:
%pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 5.0 MB/s eta 0:00:00


In [105]:
from catboost import CatBoostRegressor as Catboost

catboost_model = Pipeline([
    ("StandardScaler", StandardScaler()),
    ('catboost', Catboost(random_state=42)),
    ])

param_distribs = {
    'catboost__n_estimators': np.arange(10, 100),
    'catboost__max_depth': np.arange(4, 20),
}

catboost_search = RandomizedSearchCV(
    catboost_model,
    param_distributions=param_distribs,
    n_iter=20,
    random_state=42,
    scoring=scorer,
    cv=3,
    n_jobs=-1
    )


catboost_search.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
15 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/usr/local/lib/pyth

Learning rate set to 0.5
0:	learn: 0.7678694	total: 118ms	remaining: 2.01s
1:	learn: 0.6728582	total: 156ms	remaining: 1.25s
2:	learn: 0.6335057	total: 172ms	remaining: 862ms
3:	learn: 0.5751989	total: 185ms	remaining: 648ms
4:	learn: 0.5627762	total: 190ms	remaining: 493ms
5:	learn: 0.5215974	total: 198ms	remaining: 397ms
6:	learn: 0.4880667	total: 224ms	remaining: 352ms
7:	learn: 0.4600441	total: 237ms	remaining: 296ms
8:	learn: 0.4351721	total: 263ms	remaining: 263ms
9:	learn: 0.4161057	total: 266ms	remaining: 213ms
10:	learn: 0.4020560	total: 275ms	remaining: 175ms
11:	learn: 0.3887569	total: 277ms	remaining: 139ms
12:	learn: 0.3710154	total: 298ms	remaining: 115ms
13:	learn: 0.3617339	total: 308ms	remaining: 87.9ms
14:	learn: 0.3487859	total: 321ms	remaining: 64.2ms
15:	learn: 0.3361386	total: 329ms	remaining: 41.1ms
16:	learn: 0.3220807	total: 340ms	remaining: 20ms
17:	learn: 0.3130323	total: 350ms	remaining: 0us


RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('StandardScaler',
                                              StandardScaler()),
                                             ('catboost',
                                              <catboost.core.CatBoostRegressor object at 0x7a059b5a3bb0>)]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'catboost__max_depth': array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
                                        'catboost__n_estimators': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])},
                   random_state=42,
                   scoring=make_scorer(mean_squared_error, greater_is_better=False, response_method='predict', squared=False))

In [106]:
pd.set_option('display.max_colwidth', 10)
catboost_search.cv_results_ = pd.DataFrame(catboost_search.cv_results_)
catboost_search.cv_results_.sort_values(by=['rank_test_score'])

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
2    0.257745       0.051644      0.003937         0.000235        
1    0.911011       0.138564      0.018506         0.015702        
4    1.235471       0.265550      0.013568         0.008156        
0    0.306242       0.095174      0.010380         0.001901        
14   0.185354       0.045740      0.004658         0.000472        
18   0.204411       0.038613      0.003516         0.000250        
19   0.382340       0.074630      0.017228         0.014977        
9    0.153597       0.019052      0.006560         0.003756        
3    0.241604       0.084124      0.011767         0.003410        
16   1.601550       0.105394      0.018435         0.007115        
5    9.773978       2.116793      0.004482         0.000297        
13   5.734696       1.013210      0.016261         0.002453        
10   0.599741       0.085780      0.005415         0.002344        
11   0.109053       0.037225      0.008163         0.006243        
17   1.592341       0.139157      0.010225         0.002982        
7    0.004197       0.000855      0.000000         0.000000        
8    0.003454       0.000124      0.000000         0.000000        
12   0.011424       0.009137      0.000000         0.000000        
15   0.014442       0.000941      0.000000         0.000000        
6    0.007611       0.004550      0.000000         0.000000        

    param_catboost__n_estimators  param_catboost__max_depth     params  \
2          18                            10                  {'catb...   
1          75                            10                  {'catb...   
4          98                            10                  {'catb...   
0          88                             5                  {'catb...   
14         61                             5                  {'catb...   
18         46                             7                  {'catb...   
19         90                             7                  {'catb...   
9          74                             6                  {'catb...   
3          75                             4                  {'catb...   
16         75                            11                  {'catb...   
5          74                            14                  {'catb...   
13         50                            14                  {'catb...   
10         59                            10                  {'catb...   
11         35                             5                  {'catb...   
17         46                            12                  {'catb...   
7          82                            19                  {'catb...   
8          39                            17                  {'catb...   
12         63                            17                  {'catb...   
15         55                            18                  {'catb...   
6          50                            19                  {'catb...   

    split0_test_score  split1_test_score  split2_test_score  mean_test_score  \
2   -0.480481          -1.053818          -0.534781          -0.689693         
1   -0.431437          -1.046578          -0.618158          -0.698724         
4   -0.431948          -1.082641          -0.583422          -0.699337         
0   -0.440216          -1.080581          -0.600857          -0.707218         
14  -0.465371          -1.068500          -0.592488          -0.708787         
18  -0.432705          -1.086351          -0.607934          -0.708997         
19  -0.490709          -1.070237          -0.569850          -0.710265         
9   -0.461412          -1.052771          -0.642673          -0.718952         
3   -0.459091          -1.047330          -0.658406          -0.721609         
16  -0.492688          -1.066264          -0.634979          -0.731310         
5   -0.472747          -1.087787          -0.637893          -0.732809         
13  -0.463130          -1.095903          -0.641677         

In [107]:
catboost_search.best_params_

{'catboost__n_estimators': 18, 'catboost__max_depth': 10}

In [108]:
best_catboost_model = catboost_search.best_estimator_

In [109]:
y_pred = best_catboost_model.predict(X_train)
rmsle = root_mean_squared_error(y_train, y_pred)
rmsle

0.31303231846534124

In [110]:
y_pred = best_catboost_model.predict(X_test)
rmsle = root_mean_squared_error(y_test, y_pred)
rmsle

1.174824478878005

In [111]:
# Chang-Ki Hong(6.67) 2023
ChangKiHong = np.array([np.log(109), np.log(65), np.log(216)])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = best_catboost_model.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([4.29470032])

In [112]:
# Austin (4.97) 2023
Auntin = np.array([np.log(65), np.log(95), np.log(269)])
Auntin = Auntin.reshape(1, -1)
y_pred = best_catboost_model.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.38403209])

In [113]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([np.log(62), np.log(49), np.log(168)])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = best_catboost_model.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.00014808])

In [114]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([np.log(65), np.log(41), np.log(152)])
Choo = Choo.reshape(1, -1)
y_pred = best_catboost_model.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([2.20120885])

In [115]:
# Jae-Hwan Kim (0.44) 2023
JaeHwanKim = np.array([np.log(40), np.log(46), np.log(134)])
JaeHwanKim = JaeHwanKim.reshape(1, -1)
y_pred = best_catboost_model.predict(JaeHwanKim)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([0.68052738])