In [1]:
%pip install "scikit-learn<1.6"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 7.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.0
    Uninstalling scikit-learn-1.6.0:
      Successfully uninstalled scikit-learn-1.6.0


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/sample_data/final_df.csv', index_col=0)

# Split train and test
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

# split features and labels
X_train = train_set.drop("WAR", axis=1).to_numpy()
y_train = train_set["WAR"].copy().to_numpy()
X_test = test_set.drop("WAR", axis=1).to_numpy()
y_test = test_set["WAR"].copy().to_numpy()

In [2]:
%pip install lightgbm

In [3]:
%pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 6.6 MB/s eta 0:00:00


In [54]:
from sklearn.ensemble import StackingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
import xgboost as xgb
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

stacking_reg = StackingRegressor(
    estimators=[
        ('RandomForest_1', RandomForestRegressor(n_estimators=98, max_depth=10, random_state=42)),
        ('xgboost_1', xgb.XGBRegressor(n_estimators=90, max_depth=7, random_state=42))
    ],
    final_estimator=LinearRegression(),
    n_jobs=-1,
    cv=3
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('stacking_reg', stacking_reg)
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('stacking_reg',
                 StackingRegressor(cv=3,
                                   estimators=[('RandomForest_1',
                                                RandomForestRegressor(max_depth=10,
                                                                      n_estimators=98,
                                                                      random_state=42)),
                                               ('xgboost_1',
                                                XGBRegressor(base_score=None,
                                                             booster=None,
                                                             callbacks=None,
                                                             colsample_bylevel=None,
                                                             colsample_bynode=None,
                                                             colsample_bytree=None,
                                                             device=None,
                                                             early_stopping_roun...
                                                             interaction_constraints=None,
                                                             learning_rate=None,
                                                             max_bin=None,
                                                             max_cat_threshold=None,
                                                             max_cat_to_onehot=None,
                                                             max_delta_step=None,
                                                             max_depth=7,
                                                             max_leaves=None,
                                                             min_child_weight=None,
                                                             missing=nan,
                                                             monotone_constraints=None,
                                                             multi_strategy=None,
                                                             n_estimators=90,
                                                             n_jobs=None,
                                                             num_parallel_tree=None,
                                                             random_state=42, ...))],
                                   final_estimator=LinearRegression(),
                                   n_jobs=-1))])

In [55]:
from sklearn.metrics import root_mean_squared_error
y_pred = pipeline.predict(X_train)
rmse = root_mean_squared_error(np.exp(y_train) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.21328098962711267

In [56]:
y_pred = pipeline.predict(X_test)
rmse = root_mean_squared_error(np.exp(y_test) + 1.351, np.exp(y_pred) + 1.351)
rmse

0.9747058466900876

In [57]:
# Chang-Ki Hong (6.67) 2023
ChangKiHong = np.array([524, np.log(109), np.log(1), np.log(216), np.log(65), np.log(88), np.log(3), np.log(6), 0.332, 0.444, 0.412, 0.856])
ChangKiHong = ChangKiHong.reshape(1, -1)
y_pred = pipeline.predict(ChangKiHong)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([8.72676138])

In [50]:
# Austin (4.97) 2023
Auntin = np.array([520, np.log(87), np.log(23), np.log(269), np.log(95), np.log(53), np.log(2), np.log(7), 0.313, 0.376, 0.517, 0.893])
Auntin = Auntin.reshape(1, -1)
y_pred = pipeline.predict(Auntin)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([5.9283461])

In [51]:
# Jae-Gyun Hwang (3.14) 2023
JaeGyunHwang = np.array([407, np.log(62), np.log(6), np.log(168), np.log(49), np.log(45), np.log(1), np.log(1), 0.295, 0.366, 0.413, 0.779])
JaeGyunHwang = JaeGyunHwang.reshape(1, -1)
y_pred = pipeline.predict(JaeGyunHwang)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.55793361])

In [52]:
# Shin-Soo Choo (1.72) 2023
Choo = np.array([382, np.log(65), np.log(12), np.log(152), np.log(41), np.log(65), np.log(1), np.log(2), 0.254, 0.379, 0.398, 0.777])
Choo = Choo.reshape(1, -1)
y_pred = pipeline.predict(Choo)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([3.84734883])

In [53]:
# EunWonJung (0.74) 2023
EunWonJung = np.array([388, np.log(50), np.log(2), np.log(104), np.log(30), np.log(62), np.log(1), np.log(1), 0.222, 0.333, 0.268, 0.601])
EunWonJung = EunWonJung.reshape(1, -1)
y_pred = pipeline.predict(EunWonJung)
y_pred = np.exp(y_pred) - 1.351
y_pred

array([1.52220511])