In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/sample_data/KBO increased data edited.csv')

In [3]:
# train set과 test set 분리
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

## 득점만 가지고 linear SVM

In [4]:
R = train_set["R"].to_numpy()
R = R.reshape(-1, 1)
y = train_set["WAR"].copy().to_numpy()
y = y.reshape(-1, 1)

In [5]:
from sklearn.svm import LinearSVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

svm_reg = make_pipeline(StandardScaler(), LinearSVR(epsilon=0.5, random_state=42))
svm_reg.fit(R, y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvr', LinearSVR(epsilon=0.5, random_state=42))])

In [6]:
train_predicton = svm_reg.predict(R)
train_predicton[:5]

array([ 1.93151778,  0.00805021,  0.05079393, -0.07743724, -0.46213075])

In [7]:
y[:5]

array([[ 1.01],
       [-0.22],
       [-0.15],
       [-0.24],
       [-0.07]])

In [9]:
from sklearn.metrics import root_mean_squared_error

lin_rmse = root_mean_squared_error(y, train_predicton)
lin_rmse

0.7504614624322966

In [8]:
R_test = test_set["R"].to_numpy()
R_test = R_test.reshape(-1, 1)
y_test = test_set["WAR"].copy().to_numpy()
y_test = y_test.reshape(-1, 1)

In [10]:
final_prediction = svm_reg.predict(R_test)
final_rmse = root_mean_squared_error(y_test, final_prediction)
final_rmse

0.7352855321543373

In [11]:
# 황재균 WAR 예측
hwang = svm_reg.predict([[60]])
hwang

array([2.05974895])

In [12]:
# 로하스 WAR 예측
Rojas = svm_reg.predict([[108]])
Rojas

array([4.11144769])

In [13]:
# 김도영 WAR 예측
DO_YEONG = svm_reg.predict([[143]])
DO_YEONG

array([5.60747802])

## 득점만 가지고 nonlinear SVM

In [34]:
from sklearn.svm import SVR
svm_poly_reg = make_pipeline(StandardScaler(), SVR(kernel='poly', degree=4, C=0.01, epsilon=0.1))
svm_poly_reg.fit(R, y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(C=0.01, degree=4, kernel='poly'))])

In [35]:
train_prediction = svm_poly_reg.predict(R)
train_prediction[:5]

array([ 0.12286845, -0.01272036, -0.01453224, -0.00778795,  0.0497198 ])

In [36]:
lin_rmse = root_mean_squared_error(y, train_predicton)
lin_rmse

0.7504614624322966

In [37]:
final_prediction = svm_poly_reg.predict(R_test)
final_rmse = root_mean_squared_error(y_test, final_prediction)
final_rmse

0.7844827478648585

In [38]:
# 황재균 WAR(-0.30) 예측
hwang = svm_poly_reg.predict([[60]])
hwang

array([0.18792229])

In [39]:
# 로하스 WAR(6.50) 예측
Rojas = svm_poly_reg.predict([[108]])
Rojas

array([7.26178756])

In [40]:
# 김도영 WAR(8.32) 예측
DO_YEONG = svm_poly_reg.predict([[143]])
DO_YEONG

array([30.38079079])

In [41]:
# 최정 WAR(4.55) 예측
Choi_Jung = svm_poly_reg.predict([[93]])
Choi_Jung

array([3.20785266])

In [42]:
# 강백호 WAR(2.12) 예측
BaekHo = svm_poly_reg.predict([[92]])
BaekHo

array([3.01804309])

In [44]:
# 모델 저장
import joblib
joblib.dump(svm_poly_reg, "svm_poly_reg_with_R_model.pkl")

['svm_poly_reg_with_R_model.pkl']

## 득점, 타점만 가지고 linear SVM



In [43]:
R = train_set["R"].to_numpy()
R = R.reshape(-1, 1)

RBI = train_set["RBI"].to_numpy()
RBI = RBI.reshape(-1, 1)

R_AND_RBI = np.concatenate((R, RBI), axis=1)

y = train_set["WAR"].copy().to_numpy()
y = y.reshape(-1, 1)

In [45]:
svm_reg = make_pipeline(StandardScaler(), LinearSVR(epsilon=0.5, random_state=42))
svm_reg.fit(R_AND_RBI, y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvr', LinearSVR(epsilon=0.5, random_state=42))])

In [47]:
train_predicton = svm_reg.predict(R_AND_RBI)
train_predicton[:5]

array([ 2.04487899, -0.09756651, -0.05166506, -0.09711344, -0.47947454])

In [48]:
y[:5]

array([[ 1.01],
       [-0.22],
       [-0.15],
       [-0.24],
       [-0.07]])

In [49]:
lin_rmse = root_mean_squared_error(y, train_predicton)
lin_rmse

0.7472553007066631

In [50]:
R_test = test_set["R"].to_numpy()
R_test = R_test.reshape(-1, 1)

RBI_test = test_set["RBI"].to_numpy()
RBI_test = RBI_test.reshape(-1, 1)

R_AND_RBI_test = np.concatenate((R_test, RBI_test), axis=1)

In [51]:
final_prediction = svm_reg.predict(R_AND_RBI_test)
final_rmse = root_mean_squared_error(y_test, final_prediction)
final_rmse

0.7366753085633186

In [53]:
# 황재균 WAR(-0.30) 예측
hwang = svm_reg.predict([[60, 58]])
hwang

array([2.21333535])

In [54]:
# 로하스 WAR(6.50) 예측
Rojas = svm_reg.predict([[108, 112]])
Rojas

array([4.50886122])

## 득점, 타점만 가지고 nonlinear SVM

In [55]:
from sklearn.svm import SVR
svm_poly_reg = make_pipeline(StandardScaler(), SVR(kernel='poly', degree=4, C=0.01, epsilon=0.1))
svm_poly_reg.fit(R_AND_RBI, y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(C=0.01, degree=4, kernel='poly'))])

In [57]:
train_prediction = svm_poly_reg.predict(R_AND_RBI)
lin_rmse = root_mean_squared_error(y, train_predicton)
lin_rmse

0.7472553007066631

In [60]:
final_prediction = svm_poly_reg.predict(R_AND_RBI_test)
final_rmse = root_mean_squared_error(y_test, final_prediction)
final_rmse

0.8387986587230651

In [63]:
# 황재균 WAR(-0.30) 예측
hwang = svm_poly_reg.predict([[60, 58]])
hwang

array([0.13933294])

In [64]:
# 로하스 WAR(6.50) 예측
Rojas = svm_poly_reg.predict([[108, 112]])
Rojas

array([6.13135569])

In [65]:
# 김도영 WAR(8.32) 예측
DO_YEONG = svm_poly_reg.predict([[143, 109]])
DO_YEONG

array([13.52133253])

In [66]:
# 최정 WAR(4.55) 예측
Choi_Jung = svm_poly_reg.predict([[93, 107]])
Choi_Jung

array([3.63120434])

In [67]:
# 강백호 WAR(2.12) 예측
BaekHo = svm_poly_reg.predict([[92, 96]])
BaekHo

array([2.62668486])

In [68]:
# MLB 데이터
# 후안 소토(7.9)
Soto = svm_poly_reg.predict([[128, 109]])
Soto

array([9.49185355])

In [69]:
# 모델 저장
import joblib
joblib.dump(svm_poly_reg, "svm_poly_reg_with_R_and_RBI_model.pkl")

['svm_poly_reg_with_R_and_RBI_model.pkl']