In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('/content/sample_data/KBO_24_STAT_edited.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   WAR     50 non-null     float64
 1   AB      50 non-null     int64  
 2   R       50 non-null     int64  
 3   HR      50 non-null     int64  
 4   TB      50 non-null     int64  
 5   RBI     50 non-null     int64  
 6   BB      50 non-null     int64  
 7   IB      50 non-null     int64  
 8   SF      50 non-null     int64  
 9   AVG     50 non-null     float64
 10  OBP     50 non-null     float64
 11  SLG     50 non-null     float64
 12  OPS     50 non-null     float64
 13  wRC+    50 non-null     float64
dtypes: float64(6), int64(8)
memory usage: 5.6 KB


In [24]:
# 데이터 타입 변경
df = df.astype('float32')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   WAR     50 non-null     float32
 1   AB      50 non-null     float32
 2   R       50 non-null     float32
 3   HR      50 non-null     float32
 4   TB      50 non-null     float32
 5   RBI     50 non-null     float32
 6   BB      50 non-null     float32
 7   IB      50 non-null     float32
 8   SF      50 non-null     float32
 9   AVG     50 non-null     float32
 10  OBP     50 non-null     float32
 11  SLG     50 non-null     float32
 12  OPS     50 non-null     float32
 13  wRC+    50 non-null     float32
dtypes: float32(14)
memory usage: 2.9 KB


In [26]:
# train set과 test set 분리
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)
train_set.to_csv("KB0_24_train.csv", index = False)
test_set.to_csv("KB0_24_test.csv", index = False)

In [27]:
# 예측 변수와 타깃값 분리
X = train_set.drop("WAR", axis=1)
y = train_set["WAR"].copy()

In [51]:
X = train_set.drop("WAR", axis=1).to_numpy()
y = train_set["WAR"].copy().to_numpy()
X, y

(array([[4.530e+02, 1.020e+02, 3.000e+00, 1.740e+02, 3.600e+01, 6.000e+01,
         2.000e+00, 1.000e+00, 3.160e-01, 4.050e-01, 3.840e-01, 7.890e-01,
         1.127e+02],
        [5.090e+02, 9.000e+01, 1.100e+01, 2.330e+02, 7.500e+01, 4.700e+01,
         2.000e+00, 7.000e+00, 3.260e-01, 3.830e-01, 4.580e-01, 8.410e-01,
         1.241e+02],
        [5.330e+02, 8.300e+01, 3.400e+01, 2.600e+02, 1.070e+02, 4.900e+01,
         1.000e+00, 3.000e+00, 2.460e-01, 3.160e-01, 4.880e-01, 8.040e-01,
         1.045e+02],
        [4.680e+02, 9.300e+01, 3.700e+01, 2.780e+02, 1.070e+02, 5.500e+01,
         1.000e+00, 7.000e+00, 2.910e-01, 3.840e-01, 5.940e-01, 9.780e-01,
         1.459e+02],
        [4.930e+02, 9.200e+01, 3.300e+01, 3.090e+02, 1.150e+02, 5.500e+01,
         4.000e+00, 6.000e+00, 3.430e-01, 4.170e-01, 6.270e-01, 1.044e+00,
         1.623e+02],
        [5.240e+02, 9.600e+01, 5.000e+00, 2.150e+02, 7.300e+01, 9.600e+01,
         3.000e+00, 4.000e+00, 3.360e-01, 4.470e-01, 4.100e-01, 8.570e

In [64]:
# 스케일링
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
X_scaled = std_scaler.fit_transform(X)

In [65]:
import tensorflow as tf
W = tf.Variable(tf.random.normal([13, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

In [60]:
# 비용함수 정의
def loss_fn(model, features, labels):
  hypothesis = model(features)
  cost = tf.reduce_mean(tf.square(hypothesis - labels))
  return cost

In [71]:
learning_rate = 0.001

In [62]:
def predict(X):
    return tf.matmul(X, W) + b

In [72]:
epochs = 10000

for i in range(epochs):
    with tf.GradientTape() as tape:
        cost = loss_fn(predict, X_scaled, y)

    W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 100 == 0:
        print(f'{i} loss: {loss_fn(predict, X_scaled, y)}')

0 loss: 2.5097250938415527
100 loss: 2.509671688079834
200 loss: 2.5096187591552734
300 loss: 2.509566307067871
400 loss: 2.5095131397247314
500 loss: 2.5094614028930664
600 loss: 2.5094099044799805
700 loss: 2.5093584060668945
800 loss: 2.509307622909546
900 loss: 2.5092570781707764
1000 loss: 2.509206533432007
1100 loss: 2.5091569423675537
1200 loss: 2.5091073513031006
1300 loss: 2.5090579986572266
1400 loss: 2.5090091228485107
1500 loss: 2.508960723876953
1600 loss: 2.5089125633239746
1700 loss: 2.508864402770996
1800 loss: 2.508816957473755
1900 loss: 2.5087697505950928
2000 loss: 2.5087225437164307
2100 loss: 2.508676052093506
2200 loss: 2.50862979888916
2300 loss: 2.5085837841033936
2400 loss: 2.508538007736206
2500 loss: 2.5084924697875977
2600 loss: 2.5084471702575684
2700 loss: 2.5084023475646973
2800 loss: 2.5083577632904053
2900 loss: 2.5083136558532715
3000 loss: 2.5082695484161377
3100 loss: 2.508225917816162
3200 loss: 2.5081827640533447
3300 loss: 2.5081393718719482
3400

In [73]:
# 예측 생성
test_X = test_set.drop("WAR", axis=1).to_numpy()
test_X_scaled = std_scaler.fit_transform(X)
test_y = test_set["WAR"].copy().to_numpy()

predictions = tf.matmul(test_X_scaled, W) + b

In [74]:
predictions

<tf.Tensor: shape=(40, 1), dtype=float32, numpy=
array([[3.476756 ],
       [3.4436867],
       [3.5261447],
       [3.2516813],
       [3.2883716],
       [3.43537  ],
       [3.4230912],
       [3.4889183],
       [3.418394 ],
       [3.3551924],
       [3.3171792],
       [3.2662306],
       [3.214706 ],
       [3.3763537],
       [3.271538 ],
       [3.4948442],
       [3.3132873],
       [3.406782 ],
       [3.4752204],
       [3.4863656],
       [3.413218 ],
       [3.4220204],
       [3.4584348],
       [3.421791 ],
       [3.4539652],
       [3.5185194],
       [3.3439476],
       [3.2163975],
       [3.4582474],
       [3.3697312],
       [3.5402482],
       [3.4632943],
       [3.4355135],
       [3.4240088],
       [3.4066203],
       [3.4287174],
       [3.3442392],
       [3.415227 ],
       [3.3297904],
       [3.4157238]], dtype=float32)>